#include <Arduino.h>

String json_test = "{\n"
"  \"lat\": 48.2141,\n"
"  \"lon\": 16.3232,\n"
"  \"timezone\": \"Europe/Vienna\",\n"
"  \"timezone_offset\": 7200,\n"
"  \"current\": {\n"
"    \"dt\": 1660923318,\n"
"    \"sunrise\": 1660881258,\n"
"    \"sunset\": 1660932167,\n"
"    \"temp\": 28.21,\n"
"    \"feels_like\": 28.99,\n"
"    \"pressure\": 1008,\n"
"    \"humidity\": 53,\n"
"    \"dew_point\": 17.73,\n"
"    \"uvi\": 0.49,\n"
"    \"clouds\": 75,\n"
"    \"visibility\": 10000,\n"
"    \"wind_speed\": 4.63,\n"
"    \"wind_deg\": 130,\n"
"    \"weather\": [\n"
"      {\n"
"        \"id\": 803,\n"
"        \"main\": \"Clouds\",\n"
"        \"description\": \"Überwiegend bewölkt\",\n"
"        \"icon\": \"04d\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  \"minutely\": [\n"
"    {\n"
"      \"dt\": 1660923360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923660,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923720,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923780,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923840,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923900,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660923960,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924020,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924080,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924140,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924200,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924260,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924320,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924380,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924440,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924500,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924560,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924620,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924680,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924740,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924800,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924860,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924920,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924980,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925400,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925460,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925520,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925580,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925640,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925700,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925760,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925820,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925880,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660925940,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926000,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926060,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926120,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926180,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926240,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926300,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926660,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926720,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926780,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926840,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926900,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660926960,\n"
"      \"precipitation\": 0\n"
"    }\n"
"  ],\n"
"  \"hourly\": [\n"
"    {\n"
"      \"dt\": 1660921200,\n"
"      \"temp\": 28.63,\n"
"      \"feels_like\": 28.98,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 48,\n"
"      \"dew_point\": 16.55,\n"
"      \"uvi\": 1.58,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.79,\n"
"      \"wind_deg\": 173,\n"
"      \"wind_gust\": 7.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660924800,\n"
"      \"temp\": 28.21,\n"
"      \"feels_like\": 28.99,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 53,\n"
"      \"dew_point\": 17.73,\n"
"      \"uvi\": 0.49,\n"
"      \"clouds\": 75,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.41,\n"
"      \"wind_deg\": 164,\n"
"      \"wind_gust\": 8.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660928400,\n"
"      \"temp\": 28.14,\n"
"      \"feels_like\": 28.61,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 50,\n"
"      \"dew_point\": 16.74,\n"
"      \"uvi\": 0.13,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.82,\n"
"      \"wind_deg\": 168,\n"
"      \"wind_gust\": 7.96,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660932000,\n"
"      \"temp\": 27.44,\n"
"      \"feels_like\": 27.92,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 51,\n"
"      \"dew_point\": 16.41,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.38,\n"
"      \"wind_deg\": 171,\n"
"      \"wind_gust\": 4.79,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660935600,\n"
"      \"temp\": 26.37,\n"
"      \"feels_like\": 26.37,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 54,\n"
"      \"dew_point\": 16.32,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 62,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.84,\n"
"      \"wind_deg\": 221,\n"
"      \"wind_gust\": 6.15,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660939200,\n"
"      \"temp\": 23.98,\n"
"      \"feels_like\": 24.18,\n"
"      \"pressure\": 1011,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 17.48,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 76,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.11,\n"
"      \"wind_deg\": 235,\n"
"      \"wind_gust\": 6.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.62,\n"
"      \"rain\": {\n"
"        \"1h\": 0.66\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1660942800,\n"
"      \"temp\": 20.98,\n"
"      \"feels_like\": 21.25,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 17.26,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.44,\n"
"      \"wind_deg\": 206,\n"
"      \"wind_gust\": 6.03,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 501,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Mäßiger Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.98,\n"
"      \"rain\": {\n"
"        \"1h\": 1.4\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1660946400,\n"
"      \"temp\": 20.51,\n"
"      \"feels_like\": 20.76,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 17.04,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 88,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.99,\n"
"      \"wind_deg\": 275,\n"
"      \"wind_gust\": 7.91,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.95,\n"
"      \"rain\": {\n"
"        \"1h\": 0.71\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1660950000,\n"
"      \"temp\": 19.75,\n"
"      \"feels_like\": 19.79,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 77,\n"
"      \"dew_point\": 15.51,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 91,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.44,\n"
"      \"wind_deg\": 274,\n"
"      \"wind_gust\": 11.1,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.74\n"
"    },\n"
"    {\n"
"      \"dt\": 1660953600,\n"
"      \"temp\": 19.01,\n"
"      \"feels_like\": 19.03,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 15.04,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 92,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.51,\n"
"      \"wind_deg\": 268,\n"
"      \"wind_gust\": 12.53,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.7\n"
"    },\n"
"    {\n"
"      \"dt\": 1660957200,\n"
"      \"temp\": 18.75,\n"
"      \"feels_like\": 18.74,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 14.78,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.13,\n"
"      \"wind_deg\": 275,\n"
"      \"wind_gust\": 13.58,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.08\n"
"    },\n"
"    {\n"
"      \"dt\": 1660960800,\n"
"      \"temp\": 18.91,\n"
"      \"feels_like\": 18.89,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 14.76,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 92,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.12,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 14.08,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.08\n"
"    },\n"
"    {\n"
"      \"dt\": 1660964400,\n"
"      \"temp\": 19.11,\n"
"      \"feels_like\": 19.11,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 14.91,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 90,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.08,\n"
"      \"wind_deg\": 287,\n"
"      \"wind_gust\": 14.75,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.08\n"
"    },\n"
"    {\n"
"      \"dt\": 1660968000,\n"
"      \"temp\": 18.98,\n"
"      \"feels_like\": 18.97,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 14.88,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 92,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.45,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 13.5,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.08\n"
"    },\n"
"    {\n"
"      \"dt\": 1660971600,\n"
"      \"temp\": 19.48,\n"
"      \"feels_like\": 19.47,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 76,\n"
"      \"dew_point\": 14.97,\n"
"      \"uvi\": 0.21,\n"
"      \"clouds\": 94,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.53,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 12.25,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.06\n"
"    },\n"
"    {\n"
"      \"dt\": 1660975200,\n"
"      \"temp\": 20.22,\n"
"      \"feels_like\": 20.18,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 72,\n"
"      \"dew_point\": 14.74,\n"
"      \"uvi\": 0.74,\n"
"      \"clouds\": 95,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.69,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 11.24,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.02\n"
"    },\n"
"    {\n"
"      \"dt\": 1660978800,\n"
"      \"temp\": 20.9,\n"
"      \"feels_like\": 20.85,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 14.76,\n"
"      \"uvi\": 1.45,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.8,\n"
"      \"wind_deg\": 276,\n"
"      \"wind_gust\": 9.87,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660982400,\n"
"      \"temp\": 20.95,\n"
"      \"feels_like\": 20.93,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 14.94,\n"
"      \"uvi\": 2.57,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.82,\n"
"      \"wind_deg\": 278,\n"
"      \"wind_gust\": 9.64,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660986000,\n"
"      \"temp\": 20.54,\n"
"      \"feels_like\": 20.53,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 72,\n"
"      \"dew_point\": 15.04,\n"
"      \"uvi\": 3.74,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.2,\n"
"      \"wind_deg\": 277,\n"
"      \"wind_gust\": 10.71,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660989600,\n"
"      \"temp\": 20.37,\n"
"      \"feels_like\": 20.29,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 14.52,\n"
"      \"uvi\": 3.81,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.46,\n"
"      \"wind_deg\": 277,\n"
"      \"wind_gust\": 11.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660993200,\n"
"      \"temp\": 21.59,\n"
"      \"feels_like\": 21.53,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 66,\n"
"      \"dew_point\": 14.81,\n"
"      \"uvi\": 4.05,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.56,\n"
"      \"wind_deg\": 281,\n"
"      \"wind_gust\": 10.16,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660996800,\n"
"      \"temp\": 20.98,\n"
"      \"feels_like\": 20.94,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 14.79,\n"
"      \"uvi\": 3.74,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.09,\n"
"      \"wind_deg\": 280,\n"
"      \"wind_gust\": 10.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1661000400,\n"
"      \"temp\": 20.17,\n"
"      \"feels_like\": 20.1,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 14.42,\n"
"      \"uvi\": 2.44,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.52,\n"
"      \"wind_deg\": 276,\n"
"      \"wind_gust\": 11.7,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.1\n"
"    },\n"
"    {\n"
"      \"dt\": 1661004000,\n"
"      \"temp\": 20.08,\n"
"      \"feels_like\": 19.97,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 14.16,\n"
"      \"uvi\": 1.64,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.86,\n"
"      \"wind_deg\": 280,\n"
"      \"wind_gust\": 11.72,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.06\n"
"    },\n"
"    {\n"
"      \"dt\": 1661007600,\n"
"      \"temp\": 20.61,\n"
"      \"feels_like\": 20.48,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 14.11,\n"
"      \"uvi\": 0.89,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.56,\n"
"      \"wind_deg\": 288,\n"
"      \"wind_gust\": 11.73,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.05\n"
"    },\n"
"    {\n"
"      \"dt\": 1661011200,\n"
"      \"temp\": 20.11,\n"
"      \"feels_like\": 19.98,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 13.93,\n"
"      \"uvi\": 0.43,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.99,\n"
"      \"wind_deg\": 289,\n"
"      \"wind_gust\": 11.99,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.04\n"
"    },\n"
"    {\n"
"      \"dt\": 1661014800,\n"
"      \"temp\": 20.09,\n"
"      \"feels_like\": 19.93,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 13.7,\n"
"      \"uvi\": 0.11,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.44,\n"
"      \"wind_deg\": 296,\n"
"      \"wind_gust\": 11.74,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1661018400,\n"
"      \"temp\": 19.33,\n"
"      \"feels_like\": 19.15,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 13.64,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.47,\n"
"      \"wind_deg\": 287,\n"
"      \"wind_gust\": 12.31,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1661022000,\n"
"      \"temp\": 19.21,\n"
"      \"feels_like\": 19.07,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 72,\n"
"      \"dew_point\": 13.84,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 94,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.12,\n"
"      \"wind_deg\": 293,\n"
"      \"wind_gust\": 12.46,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1661025600,\n"
"      \"temp\": 18.81,\n"
"      \"feels_like\": 18.73,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 76,\n"
"      \"dew_point\": 14.27,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 94,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.89,\n"
"      \"wind_deg\": 289,\n"
"      \"wind_gust\": 11.88,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1661029200,\n"
"      \"temp\": 18.61,\n"
"      \"feels_like\": 18.59,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 14.7,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 96,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.25,\n"
"      \"wind_deg\": 287,\n"
"      \"wind_gust\": 11.9,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1661032800,\n"
"      \"temp\": 18.36,\n"
"      \"feels_like\": 18.37,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 14.94,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.61,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 12.37,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1661036400,\n"
"      \"temp\": 18.23,\n"
"      \"feels_like\": 18.28,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 15,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.5,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 12.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1661040000,\n"
"      \"temp\": 18.1,\n"
"      \"feels_like\": 18.13,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 14.9,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.15,\n"
"      \"wind_deg\": 290,\n"
"      \"wind_gust\": 12.2,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1661043600,\n"
"      \"temp\": 18.01,\n"
"      \"feels_like\": 18.03,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 14.83,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.07,\n"
"      \"wind_deg\": 290,\n"
"      \"wind_gust\": 11.62,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.16\n"
"    },\n"
"    {\n"
"      \"dt\": 1661047200,\n"
"      \"temp\": 17.69,\n"
"      \"feels_like\": 17.73,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 85,\n"
"      \"dew_point\": 14.82,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.76,\n"
"      \"wind_deg\": 291,\n"
"      \"wind_gust\": 11.41,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.23\n"
"    },\n"
"    {\n"
"      \"dt\": 1661050800,\n"
"      \"temp\": 17.47,\n"
"      \"feels_like\": 17.52,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 14.9,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.05,\n"
"      \"wind_deg\": 289,\n"
"      \"wind_gust\": 11.29,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.23\n"
"    },\n"
"    {\n"
"      \"dt\": 1661054400,\n"
"      \"temp\": 17.26,\n"
"      \"feels_like\": 17.34,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 88,\n"
"      \"dew_point\": 14.96,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 79,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.07,\n"
"      \"wind_deg\": 292,\n"
"      \"wind_gust\": 11.09,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.22\n"
"    },\n"
"    {\n"
"      \"dt\": 1661058000,\n"
"      \"temp\": 17.64,\n"
"      \"feels_like\": 17.71,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 15.06,\n"
"      \"uvi\": 0.16,\n"
"      \"clouds\": 83,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.35,\n"
"      \"wind_deg\": 297,\n"
"      \"wind_gust\": 11.55,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.25\n"
"    },\n"
"    {\n"
"      \"dt\": 1661061600,\n"
"      \"temp\": 18.28,\n"
"      \"feels_like\": 18.33,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 15.09,\n"
"      \"uvi\": 0.57,\n"
"      \"clouds\": 86,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.44,\n"
"      \"wind_deg\": 301,\n"
"      \"wind_gust\": 11.08,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.29\n"
"    },\n"
"    {\n"
"      \"dt\": 1661065200,\n"
"      \"temp\": 18.04,\n"
"      \"feels_like\": 18.09,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 84,\n"
"      \"dew_point\": 15.05,\n"
"      \"uvi\": 1.47,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.69,\n"
"      \"wind_deg\": 298,\n"
"      \"wind_gust\": 10.82,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.31,\n"
"      \"rain\": {\n"
"        \"1h\": 0.13\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1661068800,\n"
"      \"temp\": 18.93,\n"
"      \"feels_like\": 18.94,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 14.84,\n"
"      \"uvi\": 2.65,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.59,\n"
"      \"wind_deg\": 304,\n"
"      \"wind_gust\": 9.97,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.27\n"
"    },\n"
"    {\n"
"      \"dt\": 1661072400,\n"
"      \"temp\": 19.57,\n"
"      \"feels_like\": 19.54,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 75,\n"
"      \"dew_point\": 14.86,\n"
"      \"uvi\": 3.87,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.55,\n"
"      \"wind_deg\": 309,\n"
"      \"wind_gust\": 9.45,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.42\n"
"    },\n"
"    {\n"
"      \"dt\": 1661076000,\n"
"      \"temp\": 20.24,\n"
"      \"feels_like\": 20.17,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 14.71,\n"
"      \"uvi\": 3.58,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.97,\n"
"      \"wind_deg\": 316,\n"
"      \"wind_gust\": 9.55,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.43,\n"
"      \"rain\": {\n"
"        \"1h\": 0.15\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1661079600,\n"
"      \"temp\": 20.69,\n"
"      \"feels_like\": 20.59,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 14.31,\n"
"      \"uvi\": 3.81,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.61,\n"
"      \"wind_deg\": 324,\n"
"      \"wind_gust\": 9.46,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.48\n"
"    },\n"
"    {\n"
"      \"dt\": 1661083200,\n"
"      \"temp\": 20.64,\n"
"      \"feels_like\": 20.54,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 14.24,\n"
"      \"uvi\": 3.51,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.1,\n"
"      \"wind_deg\": 344,\n"
"      \"wind_gust\": 8.34,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.46\n"
"    },\n"
"    {\n"
"      \"dt\": 1661086800,\n"
"      \"temp\": 20.04,\n"
"      \"feels_like\": 19.9,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 14.02,\n"
"      \"uvi\": 2.45,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.57,\n"
"      \"wind_deg\": 355,\n"
"      \"wind_gust\": 8.77,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.32\n"
"    },\n"
"    {\n"
"      \"dt\": 1661090400,\n"
"      \"temp\": 20.62,\n"
"      \"feels_like\": 20.49,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 14.03,\n"
"      \"uvi\": 1.64,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.54,\n"
"      \"wind_deg\": 0,\n"
"      \"wind_gust\": 8.39,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.46\n"
"    }\n"
"  ],\n"
"  \"daily\": [\n"
"    {\n"
"      \"dt\": 1660903200,\n"
"      \"sunrise\": 1660881258,\n"
"      \"sunset\": 1660932167,\n"
"      \"moonrise\": 1660944120,\n"
"      \"moonset\": 1660912620,\n"
"      \"moon_phase\": 0.75,\n"
"      \"temp\": {\n"
"        \"day\": 30.94,\n"
"        \"min\": 20.98,\n"
"        \"max\": 32.08,\n"
"        \"night\": 20.98,\n"
"        \"eve\": 28.21,\n"
"        \"morn\": 21.54\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 30.19,\n"
"        \"night\": 21.25,\n"
"        \"eve\": 28.99,\n"
"        \"morn\": 21.66\n"
"      },\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 35,\n"
"      \"dew_point\": 13.42,\n"
"      \"wind_speed\": 6.64,\n"
"      \"wind_deg\": 170,\n"
"      \"wind_gust\": 11.82,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 501,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Mäßiger Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.98,\n"
"      \"rain\": 2.06,\n"
"      \"uvi\": 5.76\n"
"    },\n"
"    {\n"
"      \"dt\": 1660989600,\n"
"      \"sunrise\": 1660967741,\n"
"      \"sunset\": 1661018457,\n"
"      \"moonrise\": 1661032380,\n"
"      \"moonset\": 1661003100,\n"
"      \"moon_phase\": 0.79,\n"
"      \"temp\": {\n"
"        \"day\": 20.37,\n"
"        \"min\": 18.61,\n"
"        \"max\": 21.59,\n"
"        \"night\": 18.61,\n"
"        \"eve\": 20.11,\n"
"        \"morn\": 18.98\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 20.29,\n"
"        \"night\": 18.59,\n"
"        \"eve\": 19.98,\n"
"        \"morn\": 18.97\n"
"      },\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 14.52,\n"
"      \"wind_speed\": 7.56,\n"
"      \"wind_deg\": 281,\n"
"      \"wind_gust\": 14.75,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.95,\n"
"      \"rain\": 0.71,\n"
"      \"uvi\": 4.05\n"
"    },\n"
"    {\n"
"      \"dt\": 1661076000,\n"
"      \"sunrise\": 1661054224,\n"
"      \"sunset\": 1661104747,\n"
"      \"moonrise\": 0,\n"
"      \"moonset\": 1661093280,\n"
"      \"moon_phase\": 0.82,\n"
"      \"temp\": {\n"
"        \"day\": 20.24,\n"
"        \"min\": 17.26,\n"
"        \"max\": 20.69,\n"
"        \"night\": 17.51,\n"
"        \"eve\": 19.37,\n"
"        \"morn\": 17.26\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 20.17,\n"
"        \"night\": 17.46,\n"
"        \"eve\": 19.29,\n"
"        \"morn\": 17.34\n"
"      },\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 14.71,\n"
"      \"wind_speed\": 5.97,\n"
"      \"wind_deg\": 316,\n"
"      \"wind_gust\": 12.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.48,\n"
"      \"rain\": 0.6,\n"
"      \"uvi\": 3.87\n"
"    },\n"
"    {\n"
"      \"dt\": 1661162400,\n"
"      \"sunrise\": 1661140707,\n"
"      \"sunset\": 1661191035,\n"
"      \"moonrise\": 1661121120,\n"
"      \"moonset\": 1661182980,\n"
"      \"moon_phase\": 0.85,\n"
"      \"temp\": {\n"
"        \"day\": 15.3,\n"
"        \"min\": 15,\n"
"        \"max\": 17.33,\n"
"        \"night\": 16.34,\n"
"        \"eve\": 15.91,\n"
"        \"morn\": 15.98\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 15.16,\n"
"        \"night\": 15.96,\n"
"        \"eve\": 15.57,\n"
"        \"morn\": 15.91\n"
"      },\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 87,\n"
"      \"dew_point\": 13.02,\n"
"      \"wind_speed\": 5.37,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 11.42,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.97,\n"
"      \"rain\": 3.45,\n"
"      \"uvi\": 4.07\n"
"    },\n"
"    {\n"
"      \"dt\": 1661248800,\n"
"      \"sunrise\": 1661227190,\n"
"      \"sunset\": 1661277322,\n"
"      \"moonrise\": 1661210520,\n"
"      \"moonset\": 1661272140,\n"
"      \"moon_phase\": 0.88,\n"
"      \"temp\": {\n"
"        \"day\": 19.54,\n"
"        \"min\": 15.3,\n"
"        \"max\": 23.97,\n"
"        \"night\": 18.15,\n"
"        \"eve\": 23.4,\n"
"        \"morn\": 15.3\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 19.01,\n"
"        \"night\": 17.93,\n"
"        \"eve\": 23.1,\n"
"        \"morn\": 14.82\n"
"      },\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 10.44,\n"
"      \"wind_speed\": 4.5,\n"
"      \"wind_deg\": 311,\n"
"      \"wind_gust\": 10.45,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.41,\n"
"      \"rain\": 0.79,\n"
"      \"uvi\": 1.67\n"
"    },\n"
"    {\n"
"      \"dt\": 1661335200,\n"
"      \"sunrise\": 1661313673,\n"
"      \"sunset\": 1661363608,\n"
"      \"moonrise\": 1661300400,\n"
"      \"moonset\": 1661360760,\n"
"      \"moon_phase\": 0.91,\n"
"      \"temp\": {\n"
"        \"day\": 22.77,\n"
"        \"min\": 14.95,\n"
"        \"max\": 26.27,\n"
"        \"night\": 19.58,\n"
"        \"eve\": 26.27,\n"
"        \"morn\": 14.95\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 22.38,\n"
"        \"night\": 19.45,\n"
"        \"eve\": 26.27,\n"
"        \"morn\": 14.59\n"
"      },\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 11.44,\n"
"      \"wind_speed\": 3.48,\n"
"      \"wind_deg\": 340,\n"
"      \"wind_gust\": 6.48,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 802,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Mäßig bewölkt\",\n"
"          \"icon\": \"03d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 47,\n"
"      \"pop\": 0,\n"
"      \"uvi\": 2\n"
"    },\n"
"    {\n"
"      \"dt\": 1661421600,\n"
"      \"sunrise\": 1661400156,\n"
"      \"sunset\": 1661449893,\n"
"      \"moonrise\": 1661390760,\n"
"      \"moonset\": 1661448900,\n"
"      \"moon_phase\": 0.94,\n"
"      \"temp\": {\n"
"        \"day\": 23.39,\n"
"        \"min\": 17,\n"
"        \"max\": 29.27,\n"
"        \"night\": 21.73,\n"
"        \"eve\": 29.27,\n"
"        \"morn\": 17\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 23.19,\n"
"        \"night\": 21.81,\n"
"        \"eve\": 28.7,\n"
"        \"morn\": 16.87\n"
"      },\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 54,\n"
"      \"dew_point\": 13.48,\n"
"      \"wind_speed\": 3.83,\n"
"      \"wind_deg\": 323,\n"
"      \"wind_gust\": 6.32,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 99,\n"
"      \"pop\": 0.26,\n"
"      \"uvi\": 2\n"
"    },\n"
"    {\n"
"      \"dt\": 1661508000,\n"
"      \"sunrise\": 1661486639,\n"
"      \"sunset\": 1661536177,\n"
"      \"moonrise\": 1661481240,\n"
"      \"moonset\": 1661536680,\n"
"      \"moon_phase\": 0.97,\n"
"      \"temp\": {\n"
"        \"day\": 26.83,\n"
"        \"min\": 18.63,\n"
"        \"max\": 32.17,\n"
"        \"night\": 24.1,\n"
"        \"eve\": 32.17,\n"
"        \"morn\": 18.63\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 27.37,\n"
"        \"night\": 23.95,\n"
"        \"eve\": 31.01,\n"
"        \"morn\": 18.82\n"
"      },\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 52,\n"
"      \"dew_point\": 16.16,\n"
"      \"wind_speed\": 1.72,\n"
"      \"wind_deg\": 310,\n"
"      \"wind_gust\": 3.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 501,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Mäßiger Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 40,\n"
"      \"pop\": 0.72,\n"
"      \"rain\": 3.29,\n"
"      \"uvi\": 2\n"
"    }\n"
"  ],\n"
"  \"alerts\": [\n"
"    {\n"
"      \"sender_name\": \"ZAMG Zentralanstalt für Meteorologie und Geodynamik\",\n"
"      \"event\": \"Heatwarning\",\n"
"      \"start\": 1660860000,\n"
"      \"end\": 1660946399,\n"
"      \"description\": \"Increased heat stress must be expected.\",\n"
"      \"tags\": [\n"
"        \"Extreme temperature value\"\n"
"      ]\n"
"    },\n"
"    {\n"
"      \"sender_name\": \"ZAMG Zentralanstalt für Meteorologie und Geodynamik\",\n"
"      \"event\": \"Thunderstormwarning\",\n"
"      \"start\": 1660924800,\n"
"      \"end\": 1660953600,\n"
"      \"description\": \"Thunderstorms with gusts and hail are expected.\",\n"
"      \"tags\": [\n"
"        \"Thunderstorm\"\n"
"      ]\n"
"    }\n"
"  ]\n"
"}";