#include <Arduino.h>

String json_test = "{\n"
"  \"lat\": 48.2141,\n"
"  \"lon\": 16.3232,\n"
"  \"timezone\": \"Europe/Vienna\",\n"
"  \"timezone_offset\": 7200,\n"
"  \"current\": {\n"
"    \"dt\": 1660304003,\n"
"    \"sunrise\": 1660275879,\n"
"    \"sunset\": 1660328105,\n"
"    \"temp\": 25.92,\n"
"    \"feels_like\": 25.64,\n"
"    \"pressure\": 1019,\n"
"    \"humidity\": 41,\n"
"    \"dew_point\": 11.67,\n"
"    \"uvi\": 5.28,\n"
"    \"clouds\": 20,\n"
"    \"visibility\": 10000,\n"
"    \"wind_speed\": 2.57,\n"
"    \"wind_deg\": 40,\n"
"    \"rain\":\n"
"      {\n"
"        \"1h\": 3.3\n"
"      }\n"
"    ,\n"
"    \"weather\": [\n"
"      {\n"
"        \"id\": 801,\n"
"        \"main\": \"Clouds\",\n"
"        \"description\": \"Ein paar Wolken\",\n"
"        \"icon\": \"02d\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  \"minutely\": [\n"
"    {\n"
"      \"dt\": 1660304040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304400,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304460,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304520,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304580,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304640,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304700,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304760,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304820,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304880,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660304940,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305000,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305060,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305120,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305180,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305240,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305300,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305660,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305720,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305780,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305840,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305900,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305960,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306020,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306080,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306140,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306200,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306260,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306320,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306380,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306440,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306500,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306560,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306620,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306680,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306740,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306800,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306860,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306920,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660306980,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307400,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307460,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307520,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307580,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660307640,\n"
"      \"precipitation\": 0\n"
"    }\n"
"  ],\n"
"  \"hourly\": [\n"
"    {\n"
"      \"dt\": 1660302000,\n"
"      \"temp\": 25.99,\n"
"      \"feels_like\": 25.99,\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 39,\n"
"      \"dew_point\": 10.98,\n"
"      \"uvi\": 5.7,\n"
"      \"clouds\": 20,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.8,\n"
"      \"wind_deg\": 88,\n"
"      \"wind_gust\": 3.06,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.16\n"
"    },\n"
"    {\n"
"      \"dt\": 1660305600,\n"
"      \"temp\": 25.92,\n"
"      \"feels_like\": 25.64,\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 41,\n"
"      \"dew_point\": 11.67,\n"
"      \"uvi\": 5.28,\n"
"      \"clouds\": 20,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.68,\n"
"      \"wind_deg\": 94,\n"
"      \"wind_gust\": 3.44,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.16\n"
"    },\n"
"    {\n"
"      \"dt\": 1660309200,\n"
"      \"temp\": 25.91,\n"
"      \"feels_like\": 25.55,\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 38,\n"
"      \"dew_point\": 10.52,\n"
"      \"uvi\": 2.19,\n"
"      \"clouds\": 33,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.92,\n"
"      \"wind_deg\": 91,\n"
"      \"wind_gust\": 3.46,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 802,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Mäßig bewölkt\",\n"
"          \"icon\": \"03d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660312800,\n"
"      \"temp\": 26.1,\n"
"      \"feels_like\": 26.1,\n"
"      \"pressure\": 1018,\n"
"      \"humidity\": 36,\n"
"      \"dew_point\": 9.88,\n"
"      \"uvi\": 1.5,\n"
"      \"clouds\": 44,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.86,\n"
"      \"wind_deg\": 64,\n"
"      \"wind_gust\": 3.51,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 802,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Mäßig bewölkt\",\n"
"          \"icon\": \"03d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660316400,\n"
"      \"temp\": 25.76,\n"
"      \"feels_like\": 25.31,\n"
"      \"pressure\": 1018,\n"
"      \"humidity\": 35,\n"
"      \"dew_point\": 9.16,\n"
"      \"uvi\": 0.84,\n"
"      \"clouds\": 57,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.71,\n"
"      \"wind_deg\": 61,\n"
"      \"wind_gust\": 3.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.08\n"
"    },\n"
"    {\n"
"      \"dt\": 1660320000,\n"
"      \"temp\": 25.14,\n"
"      \"feels_like\": 24.6,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 34,\n"
"      \"dew_point\": 8.19,\n"
"      \"uvi\": 0.54,\n"
"      \"clouds\": 69,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 0.82,\n"
"      \"wind_deg\": 47,\n"
"      \"wind_gust\": 2.48,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660323600,\n"
"      \"temp\": 24.45,\n"
"      \"feels_like\": 23.84,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 34,\n"
"      \"dew_point\": 7.48,\n"
"      \"uvi\": 0.16,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.37,\n"
"      \"wind_deg\": 1,\n"
"      \"wind_gust\": 2.53,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660327200,\n"
"      \"temp\": 22.9,\n"
"      \"feels_like\": 22.26,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 39,\n"
"      \"dew_point\": 8.01,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 83,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.14,\n"
"      \"wind_deg\": 15,\n"
"      \"wind_gust\": 4.77,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660330800,\n"
"      \"temp\": 21.54,\n"
"      \"feels_like\": 20.87,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 43,\n"
"      \"dew_point\": 8.22,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.35,\n"
"      \"wind_deg\": 5,\n"
"      \"wind_gust\": 3.33,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660334400,\n"
"      \"temp\": 21.22,\n"
"      \"feels_like\": 20.55,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 44,\n"
"      \"dew_point\": 8.31,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.32,\n"
"      \"wind_deg\": 335,\n"
"      \"wind_gust\": 2.91,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660338000,\n"
"      \"temp\": 21.05,\n"
"      \"feels_like\": 20.39,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 45,\n"
"      \"dew_point\": 8.51,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.15,\n"
"      \"wind_deg\": 318,\n"
"      \"wind_gust\": 2.04,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660341600,\n"
"      \"temp\": 19.72,\n"
"      \"feels_like\": 19.03,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 8.59,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.73,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 2.59,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660345200,\n"
"      \"temp\": 18.72,\n"
"      \"feels_like\": 18.01,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 52,\n"
"      \"dew_point\": 8.64,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 82,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.63,\n"
"      \"wind_deg\": 296,\n"
"      \"wind_gust\": 2.35,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660348800,\n"
"      \"temp\": 18.23,\n"
"      \"feels_like\": 17.52,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 54,\n"
"      \"dew_point\": 8.66,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 75,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.82,\n"
"      \"wind_deg\": 299,\n"
"      \"wind_gust\": 2.71,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660352400,\n"
"      \"temp\": 17.69,\n"
"      \"feels_like\": 16.98,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 8.67,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 77,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.93,\n"
"      \"wind_deg\": 299,\n"
"      \"wind_gust\": 2.92,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660356000,\n"
"      \"temp\": 17.06,\n"
"      \"feels_like\": 16.36,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 59,\n"
"      \"dew_point\": 8.71,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 69,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.12,\n"
"      \"wind_deg\": 289,\n"
"      \"wind_gust\": 3.06,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660359600,\n"
"      \"temp\": 16.59,\n"
"      \"feels_like\": 15.9,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 61,\n"
"      \"dew_point\": 8.95,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 76,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.29,\n"
"      \"wind_deg\": 296,\n"
"      \"wind_gust\": 3.71,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660363200,\n"
"      \"temp\": 16.17,\n"
"      \"feels_like\": 15.51,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 64,\n"
"      \"dew_point\": 9.1,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 78,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.46,\n"
"      \"wind_deg\": 295,\n"
"      \"wind_gust\": 4.41,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660366800,\n"
"      \"temp\": 17.01,\n"
"      \"feels_like\": 16.39,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 62,\n"
"      \"dew_point\": 9.4,\n"
"      \"uvi\": 0.23,\n"
"      \"clouds\": 81,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.52,\n"
"      \"wind_deg\": 300,\n"
"      \"wind_gust\": 5.21,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660370400,\n"
"      \"temp\": 18.55,\n"
"      \"feels_like\": 17.95,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 57,\n"
"      \"dew_point\": 9.64,\n"
"      \"uvi\": 0.75,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.93,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 5.54,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660374000,\n"
"      \"temp\": 20.36,\n"
"      \"feels_like\": 19.84,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 53,\n"
"      \"dew_point\": 10.23,\n"
"      \"uvi\": 1.61,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.54,\n"
"      \"wind_deg\": 310,\n"
"      \"wind_gust\": 5.49,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660377600,\n"
"      \"temp\": 22.88,\n"
"      \"feels_like\": 22.48,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 48,\n"
"      \"dew_point\": 11.19,\n"
"      \"uvi\": 2.77,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.75,\n"
"      \"wind_deg\": 319,\n"
"      \"wind_gust\": 5.36,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660381200,\n"
"      \"temp\": 25.11,\n"
"      \"feels_like\": 24.83,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 44,\n"
"      \"dew_point\": 11.96,\n"
"      \"uvi\": 3.96,\n"
"      \"clouds\": 72,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.87,\n"
"      \"wind_deg\": 333,\n"
"      \"wind_gust\": 5.17,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660384800,\n"
"      \"temp\": 26.77,\n"
"      \"feels_like\": 26.75,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 41,\n"
"      \"dew_point\": 12.38,\n"
"      \"uvi\": 4.16,\n"
"      \"clouds\": 68,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.99,\n"
"      \"wind_deg\": 342,\n"
"      \"wind_gust\": 5.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660388400,\n"
"      \"temp\": 27.76,\n"
"      \"feels_like\": 27.34,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 38,\n"
"      \"dew_point\": 11.98,\n"
"      \"uvi\": 4.41,\n"
"      \"clouds\": 74,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.98,\n"
"      \"wind_deg\": 347,\n"
"      \"wind_gust\": 4.69,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660392000,\n"
"      \"temp\": 27.79,\n"
"      \"feels_like\": 27.36,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 38,\n"
"      \"dew_point\": 11.9,\n"
"      \"uvi\": 4.08,\n"
"      \"clouds\": 78,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.48,\n"
"      \"wind_deg\": 359,\n"
"      \"wind_gust\": 4.84,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660395600,\n"
"      \"temp\": 26.55,\n"
"      \"feels_like\": 26.55,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 41,\n"
"      \"dew_point\": 12.07,\n"
"      \"uvi\": 2.66,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.87,\n"
"      \"wind_deg\": 6,\n"
"      \"wind_gust\": 5.05,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660399200,\n"
"      \"temp\": 26.87,\n"
"      \"feels_like\": 26.82,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 41,\n"
"      \"dew_point\": 12.38,\n"
"      \"uvi\": 1.82,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.94,\n"
"      \"wind_deg\": 355,\n"
"      \"wind_gust\": 5.53,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.27\n"
"    },\n"
"    {\n"
"      \"dt\": 1660402800,\n"
"      \"temp\": 25.82,\n"
"      \"feels_like\": 25.68,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 47,\n"
"      \"dew_point\": 13.5,\n"
"      \"uvi\": 1.02,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.9,\n"
"      \"wind_deg\": 0,\n"
"      \"wind_gust\": 5.91,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.46\n"
"    },\n"
"    {\n"
"      \"dt\": 1660406400,\n"
"      \"temp\": 23.89,\n"
"      \"feels_like\": 23.8,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 14.15,\n"
"      \"uvi\": 0.36,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.12,\n"
"      \"wind_deg\": 352,\n"
"      \"wind_gust\": 6.5,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.46,\n"
"      \"rain\": {\n"
"        \"1h\": 0.22\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1660410000,\n"
"      \"temp\": 23.49,\n"
"      \"feels_like\": 23.38,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 57,\n"
"      \"dew_point\": 14.31,\n"
"      \"uvi\": 0.1,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.86,\n"
"      \"wind_deg\": 351,\n"
"      \"wind_gust\": 5.89,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.49\n"
"    },\n"
"    {\n"
"      \"dt\": 1660413600,\n"
"      \"temp\": 21.9,\n"
"      \"feels_like\": 21.82,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 64,\n"
"      \"dew_point\": 14.48,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.54,\n"
"      \"wind_deg\": 352,\n"
"      \"wind_gust\": 6.54,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.5\n"
"    },\n"
"    {\n"
"      \"dt\": 1660417200,\n"
"      \"temp\": 20.5,\n"
"      \"feels_like\": 20.43,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 14.59,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 90,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.15,\n"
"      \"wind_deg\": 343,\n"
"      \"wind_gust\": 7.18,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.11\n"
"    },\n"
"    {\n"
"      \"dt\": 1660420800,\n"
"      \"temp\": 19.64,\n"
"      \"feels_like\": 19.59,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 74,\n"
"      \"dew_point\": 14.62,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.15,\n"
"      \"wind_deg\": 325,\n"
"      \"wind_gust\": 7.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.07\n"
"    },\n"
"    {\n"
"      \"dt\": 1660424400,\n"
"      \"temp\": 18.81,\n"
"      \"feels_like\": 18.78,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 14.71,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 88,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.99,\n"
"      \"wind_deg\": 312,\n"
"      \"wind_gust\": 7.21,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.07\n"
"    },\n"
"    {\n"
"      \"dt\": 1660428000,\n"
"      \"temp\": 17.98,\n"
"      \"feels_like\": 17.97,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 14.71,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 82,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.9,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 6.64,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.06\n"
"    },\n"
"    {\n"
"      \"dt\": 1660431600,\n"
"      \"temp\": 17.49,\n"
"      \"feels_like\": 17.49,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 84,\n"
"      \"dew_point\": 14.56,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 77,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.92,\n"
"      \"wind_deg\": 301,\n"
"      \"wind_gust\": 6.8,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660435200,\n"
"      \"temp\": 17.19,\n"
"      \"feels_like\": 17.21,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 14.54,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 74,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.99,\n"
"      \"wind_deg\": 302,\n"
"      \"wind_gust\": 7.29,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1660438800,\n"
"      \"temp\": 17.33,\n"
"      \"feels_like\": 17.34,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 85,\n"
"      \"dew_point\": 14.55,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 76,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.02,\n"
"      \"wind_deg\": 304,\n"
"      \"wind_gust\": 7.43,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660442400,\n"
"      \"temp\": 17.78,\n"
"      \"feels_like\": 17.78,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 14.59,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.11,\n"
"      \"wind_deg\": 305,\n"
"      \"wind_gust\": 7.11,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660446000,\n"
"      \"temp\": 17.95,\n"
"      \"feels_like\": 17.94,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 14.68,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 85,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.33,\n"
"      \"wind_deg\": 300,\n"
"      \"wind_gust\": 7.33,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660449600,\n"
"      \"temp\": 17.92,\n"
"      \"feels_like\": 17.93,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 14.68,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 89,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.41,\n"
"      \"wind_deg\": 297,\n"
"      \"wind_gust\": 7.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660453200,\n"
"      \"temp\": 18,\n"
"      \"feels_like\": 18,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 14.68,\n"
"      \"uvi\": 0.26,\n"
"      \"clouds\": 91,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.61,\n"
"      \"wind_deg\": 299,\n"
"      \"wind_gust\": 8.24,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660456800,\n"
"      \"temp\": 18.46,\n"
"      \"feels_like\": 18.42,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 14.69,\n"
"      \"uvi\": 0.83,\n"
"      \"clouds\": 92,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.61,\n"
"      \"wind_deg\": 305,\n"
"      \"wind_gust\": 7.81,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660460400,\n"
"      \"temp\": 19.23,\n"
"      \"feels_like\": 19.22,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 77,\n"
"      \"dew_point\": 14.82,\n"
"      \"uvi\": 1.82,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4,\n"
"      \"wind_deg\": 308,\n"
"      \"wind_gust\": 6.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660464000,\n"
"      \"temp\": 20.65,\n"
"      \"feels_like\": 20.62,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 15.03,\n"
"      \"uvi\": 3.15,\n"
"      \"clouds\": 95,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.08,\n"
"      \"wind_deg\": 312,\n"
"      \"wind_gust\": 5.98,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660467600,\n"
"      \"temp\": 22.65,\n"
"      \"feels_like\": 22.59,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 62,\n"
"      \"dew_point\": 14.95,\n"
"      \"uvi\": 4.52,\n"
"      \"clouds\": 85,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.65,\n"
"      \"wind_deg\": 329,\n"
"      \"wind_gust\": 4.79,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1660471200,\n"
"      \"temp\": 23.21,\n"
"      \"feels_like\": 23.15,\n"
"      \"pressure\": 1011,\n"
"      \"humidity\": 60,\n"
"      \"dew_point\": 14.78,\n"
"      \"uvi\": 4.82,\n"
"      \"clouds\": 85,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.59,\n"
"      \"wind_deg\": 340,\n"
"      \"wind_gust\": 4.32,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    }\n"
"  ],\n"
"  \"daily\": [\n"
"    {\n"
"      \"dt\": 1660298400,\n"
"      \"sunrise\": 1660275879,\n"
"      \"sunset\": 1660328105,\n"
"      \"moonrise\": 1660330920,\n"
"      \"moonset\": 1660275480,\n"
"      \"moon_phase\": 0.5,\n"
"      \"temp\": {\n"
"        \"day\": 25.58,\n"
"        \"min\": 15.83,\n"
"        \"max\": 26.1,\n"
"        \"night\": 21.05,\n"
"        \"eve\": 25.14,\n"
"        \"morn\": 15.83\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 25.19,\n"
"        \"night\": 20.39,\n"
"        \"eve\": 24.6,\n"
"        \"morn\": 15.14\n"
"      },\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 38,\n"
"      \"dew_point\": 10.22,\n"
"      \"wind_speed\": 2.86,\n"
"      \"wind_deg\": 64,\n"
"      \"wind_gust\": 4.77,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 21,\n"
"      \"pop\": 0.2,\n"
"      \"uvi\": 5.7\n"
"    },\n"
"    {\n"
"      \"dt\": 1660384800,\n"
"      \"sunrise\": 1660362361,\n"
"      \"sunset\": 1660414403,\n"
"      \"moonrise\": 1660418640,\n"
"      \"moonset\": 1660367040,\n"
"      \"moon_phase\": 0.55,\n"
"      \"temp\": {\n"
"        \"day\": 26.77,\n"
"        \"min\": 16.17,\n"
"        \"max\": 27.79,\n"
"        \"night\": 18.81,\n"
"        \"eve\": 23.89,\n"
"        \"morn\": 16.17\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 26.75,\n"
"        \"night\": 18.78,\n"
"        \"eve\": 23.8,\n"
"        \"morn\": 15.51\n"
"      },\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 41,\n"
"      \"dew_point\": 12.38,\n"
"      \"wind_speed\": 4.9,\n"
"      \"wind_deg\": 0,\n"
"      \"wind_gust\": 7.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 68,\n"
"      \"pop\": 0.5,\n"
"      \"rain\": 0.22,\n"
"      \"uvi\": 4.41\n"
"    },\n"
"    {\n"
"      \"dt\": 1660471200,\n"
"      \"sunrise\": 1660448844,\n"
"      \"sunset\": 1660500700,\n"
"      \"moonrise\": 1660506180,\n"
"      \"moonset\": 1660458360,\n"
"      \"moon_phase\": 0.59,\n"
"      \"temp\": {\n"
"        \"day\": 23.21,\n"
"        \"min\": 17.19,\n"
"        \"max\": 25.74,\n"
"        \"night\": 20.4,\n"
"        \"eve\": 25.41,\n"
"        \"morn\": 17.92\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 23.15,\n"
"        \"night\": 20.35,\n"
"        \"eve\": 25.34,\n"
"        \"morn\": 17.93\n"
"      },\n"
"      \"pressure\": 1011,\n"
"      \"humidity\": 60,\n"
"      \"dew_point\": 14.78,\n"
"      \"wind_speed\": 4.08,\n"
"      \"wind_deg\": 312,\n"
"      \"wind_gust\": 8.24,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 85,\n"
"      \"pop\": 0.14,\n"
"      \"uvi\": 5.11\n"
"    },\n"
"    {\n"
"      \"dt\": 1660557600,\n"
"      \"sunrise\": 1660535327,\n"
"      \"sunset\": 1660586996,\n"
"      \"moonrise\": 1660593600,\n"
"      \"moonset\": 1660549560,\n"
"      \"moon_phase\": 0.62,\n"
"      \"temp\": {\n"
"        \"day\": 28.99,\n"
"        \"min\": 17.95,\n"
"        \"max\": 31.91,\n"
"        \"night\": 22.47,\n"
"        \"eve\": 30.65,\n"
"        \"morn\": 17.95\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 28.6,\n"
"        \"night\": 22.42,\n"
"        \"eve\": 29.3,\n"
"        \"morn\": 17.86\n"
"      },\n"
"      \"pressure\": 1006,\n"
"      \"humidity\": 40,\n"
"      \"dew_point\": 14.09,\n"
"      \"wind_speed\": 5.87,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 12.21,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 0,\n"
"      \"pop\": 0.34,\n"
"      \"uvi\": 6.21\n"
"    },\n"
"    {\n"
"      \"dt\": 1660644000,\n"
"      \"sunrise\": 1660621810,\n"
"      \"sunset\": 1660673291,\n"
"      \"moonrise\": 1660681020,\n"
"      \"moonset\": 1660640460,\n"
"      \"moon_phase\": 0.66,\n"
"      \"temp\": {\n"
"        \"day\": 28.65,\n"
"        \"min\": 19.2,\n"
"        \"max\": 31.89,\n"
"        \"night\": 23.96,\n"
"        \"eve\": 31.28,\n"
"        \"morn\": 19.2\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 27.89,\n"
"        \"night\": 23.46,\n"
"        \"eve\": 29.61,\n"
"        \"morn\": 19.13\n"
"      },\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 35,\n"
"      \"dew_point\": 11.84,\n"
"      \"wind_speed\": 6.26,\n"
"      \"wind_deg\": 287,\n"
"      \"wind_gust\": 13.36,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 52,\n"
"      \"pop\": 0.63,\n"
"      \"rain\": 0.29,\n"
"      \"uvi\": 6.37\n"
"    },\n"
"    {\n"
"      \"dt\": 1660730400,\n"
"      \"sunrise\": 1660708292,\n"
"      \"sunset\": 1660759584,\n"
"      \"moonrise\": 1660768500,\n"
"      \"moonset\": 1660731240,\n"
"      \"moon_phase\": 0.69,\n"
"      \"temp\": {\n"
"        \"day\": 30.42,\n"
"        \"min\": 21.11,\n"
"        \"max\": 34.2,\n"
"        \"night\": 26.68,\n"
"        \"eve\": 34.2,\n"
"        \"morn\": 21.11\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 29.51,\n"
"        \"night\": 26.73,\n"
"        \"eve\": 32.63,\n"
"        \"morn\": 20.56\n"
"      },\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 34,\n"
"      \"dew_point\": 12.53,\n"
"      \"wind_speed\": 6.03,\n"
"      \"wind_deg\": 158,\n"
"      \"wind_gust\": 8.45,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 4,\n"
"      \"pop\": 0,\n"
"      \"uvi\": 7\n"
"    },\n"
"    {\n"
"      \"dt\": 1660816800,\n"
"      \"sunrise\": 1660794775,\n"
"      \"sunset\": 1660845876,\n"
"      \"moonrise\": 1660856160,\n"
"      \"moonset\": 1660822020,\n"
"      \"moon_phase\": 0.73,\n"
"      \"temp\": {\n"
"        \"day\": 23.05,\n"
"        \"min\": 17.6,\n"
"        \"max\": 28.24,\n"
"        \"night\": 17.87,\n"
"        \"eve\": 22.02,\n"
"        \"morn\": 22.07\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 23,\n"
"        \"night\": 17.64,\n"
"        \"eve\": 22.11,\n"
"        \"morn\": 21.98\n"
"      },\n"
"      \"pressure\": 1006,\n"
"      \"humidity\": 61,\n"
"      \"dew_point\": 14.86,\n"
"      \"wind_speed\": 7.61,\n"
"      \"wind_deg\": 272,\n"
"      \"wind_gust\": 14.41,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 501,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Mäßiger Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.98,\n"
"      \"rain\": 4.73,\n"
"      \"uvi\": 7\n"
"    },\n"
"    {\n"
"      \"dt\": 1660903200,\n"
"      \"sunrise\": 1660881258,\n"
"      \"sunset\": 1660932167,\n"
"      \"moonrise\": 1660944120,\n"
"      \"moonset\": 1660912620,\n"
"      \"moon_phase\": 0.75,\n"
"      \"temp\": {\n"
"        \"day\": 20.39,\n"
"        \"min\": 16.74,\n"
"        \"max\": 25.26,\n"
"        \"night\": 16.74,\n"
"        \"eve\": 22.99,\n"
"        \"morn\": 17.67\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 19.95,\n"
"        \"night\": 16.32,\n"
"        \"eve\": 22.62,\n"
"        \"morn\": 17.24\n"
"      },\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 11.02,\n"
"      \"wind_speed\": 8.11,\n"
"      \"wind_deg\": 275,\n"
"      \"wind_gust\": 14.79,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.28,\n"
"      \"uvi\": 7\n"
"    }\n"
"  ]\n"
"}";