#include <Arduino.h>

String json_test = "{\n"
"  \"lat\": 48.2141,\n"
"  \"lon\": 16.3232,\n"
"  \"timezone\": \"Europe/Vienna\",\n"
"  \"timezone_offset\": 7200,\n"
"  \"current\": {\n"
"    \"dt\": 1682016048,\n"
"    \"sunrise\": 1681962968,\n"
"    \"sunset\": 1682013053,\n"
"    \"temp\": 12.84,\n"
"    \"feels_like\": 12.09,\n"
"    \"pressure\": 1017,\n"
"    \"humidity\": 73,\n"
"    \"dew_point\": 8.13,\n"
"    \"uvi\": 0,\n"
"    \"clouds\": 99,\n"
"    \"visibility\": 10000,\n"
"    \"wind_speed\": 0.45,\n"
"    \"wind_deg\": 153,\n"
"    \"wind_gust\": 0.89,\n"
"    \"weather\": [\n"
"      {\n"
"        \"id\": 804,\n"
"        \"main\": \"Clouds\",\n"
"        \"description\": \"Bedeckt\",\n"
"        \"icon\": \"04n\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  \"minutely\": [\n"
"    {\n"
"      \"dt\": 1682016060,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016120,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016180,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016240,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016300,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016660,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016720,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016780,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016840,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016900,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682016960,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017020,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017080,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017140,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017200,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017260,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017320,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017380,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017440,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017500,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017560,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017620,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017680,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017740,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017800,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017860,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017920,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017980,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018400,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018460,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018520,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018580,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018640,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018700,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018760,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018820,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018880,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682018940,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019000,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019060,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019120,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019180,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019240,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019300,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682019660,\n"
"      \"precipitation\": 0\n"
"    }\n"
"  ],\n"
"  \"hourly\": [\n"
"    {\n"
"      \"dt\": 1682013600,\n"
"      \"temp\": 12.62,\n"
"      \"feels_like\": 11.87,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 74,\n"
"      \"dew_point\": 8.11,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 96,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.98,\n"
"      \"wind_deg\": 129,\n"
"      \"wind_gust\": 4.59,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682017200,\n"
"      \"temp\": 12.84,\n"
"      \"feels_like\": 12.09,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 73,\n"
"      \"dew_point\": 8.13,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.73,\n"
"      \"wind_deg\": 138,\n"
"      \"wind_gust\": 2.68,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682020800,\n"
"      \"temp\": 12.4,\n"
"      \"feels_like\": 11.65,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 75,\n"
"      \"dew_point\": 8.1,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.57,\n"
"      \"wind_deg\": 136,\n"
"      \"wind_gust\": 1.61,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682024400,\n"
"      \"temp\": 11.72,\n"
"      \"feels_like\": 10.93,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 76,\n"
"      \"dew_point\": 7.64,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 99,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.51,\n"
"      \"wind_deg\": 123,\n"
"      \"wind_gust\": 1.65,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682028000,\n"
"      \"temp\": 10.88,\n"
"      \"feels_like\": 10.09,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 7.39,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.6,\n"
"      \"wind_deg\": 121,\n"
"      \"wind_gust\": 1.77,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682031600,\n"
"      \"temp\": 10.13,\n"
"      \"feels_like\": 9.31,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 7.02,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 95,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.68,\n"
"      \"wind_deg\": 114,\n"
"      \"wind_gust\": 2.24,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682035200,\n"
"      \"temp\": 9.54,\n"
"      \"feels_like\": 8.89,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 6.33,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 91,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.74,\n"
"      \"wind_deg\": 107,\n"
"      \"wind_gust\": 4.82,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682038800,\n"
"      \"temp\": 9.51,\n"
"      \"feels_like\": 8.64,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 6.25,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 78,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.98,\n"
"      \"wind_deg\": 118,\n"
"      \"wind_gust\": 6.39,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682042400,\n"
"      \"temp\": 9.11,\n"
"      \"feels_like\": 7.94,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 6.14,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 68,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.27,\n"
"      \"wind_deg\": 126,\n"
"      \"wind_gust\": 7.28,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682046000,\n"
"      \"temp\": 8.95,\n"
"      \"feels_like\": 7.78,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 6.03,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 69,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.23,\n"
"      \"wind_deg\": 131,\n"
"      \"wind_gust\": 7.63,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682049600,\n"
"      \"temp\": 8.84,\n"
"      \"feels_like\": 7.72,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 5.8,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 68,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.14,\n"
"      \"wind_deg\": 130,\n"
"      \"wind_gust\": 7.65,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682053200,\n"
"      \"temp\": 9.48,\n"
"      \"feels_like\": 8.65,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 5.71,\n"
"      \"uvi\": 0.17,\n"
"      \"clouds\": 70,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.93,\n"
"      \"wind_deg\": 130,\n"
"      \"wind_gust\": 7.8,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682056800,\n"
"      \"temp\": 10.82,\n"
"      \"feels_like\": 9.81,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 5.54,\n"
"      \"uvi\": 0.58,\n"
"      \"clouds\": 67,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.37,\n"
"      \"wind_deg\": 131,\n"
"      \"wind_gust\": 7.66,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682060400,\n"
"      \"temp\": 12.51,\n"
"      \"feels_like\": 11.38,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 60,\n"
"      \"dew_point\": 4.77,\n"
"      \"uvi\": 1.44,\n"
"      \"clouds\": 14,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.23,\n"
"      \"wind_deg\": 132,\n"
"      \"wind_gust\": 7.7,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682064000,\n"
"      \"temp\": 14.14,\n"
"      \"feels_like\": 12.99,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 53,\n"
"      \"dew_point\": 4.37,\n"
"      \"uvi\": 2.52,\n"
"      \"clouds\": 10,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.1,\n"
"      \"wind_deg\": 136,\n"
"      \"wind_gust\": 7.38,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682067600,\n"
"      \"temp\": 15.23,\n"
"      \"feels_like\": 14.06,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 48,\n"
"      \"dew_point\": 4.14,\n"
"      \"uvi\": 3.64,\n"
"      \"clouds\": 9,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.6,\n"
"      \"wind_deg\": 136,\n"
"      \"wind_gust\": 6.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682071200,\n"
"      \"temp\": 15.85,\n"
"      \"feels_like\": 14.77,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 4.96,\n"
"      \"uvi\": 4.4,\n"
"      \"clouds\": 9,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.66,\n"
"      \"wind_deg\": 133,\n"
"      \"wind_gust\": 6,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682074800,\n"
"      \"temp\": 16.4,\n"
"      \"feels_like\": 15.35,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 48,\n"
"      \"dew_point\": 5.35,\n"
"      \"uvi\": 4.68,\n"
"      \"clouds\": 10,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.3,\n"
"      \"wind_deg\": 131,\n"
"      \"wind_gust\": 5.25,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682078400,\n"
"      \"temp\": 16.81,\n"
"      \"feels_like\": 15.77,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 47,\n"
"      \"dew_point\": 5.3,\n"
"      \"uvi\": 4.32,\n"
"      \"clouds\": 16,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.97,\n"
"      \"wind_deg\": 130,\n"
"      \"wind_gust\": 4.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682082000,\n"
"      \"temp\": 16.32,\n"
"      \"feels_like\": 15.23,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 47,\n"
"      \"dew_point\": 5.02,\n"
"      \"uvi\": 1.78,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.5,\n"
"      \"wind_deg\": 131,\n"
"      \"wind_gust\": 4.09,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1682085600,\n"
"      \"temp\": 15.66,\n"
"      \"feels_like\": 14.61,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 51,\n"
"      \"dew_point\": 5.44,\n"
"      \"uvi\": 1.21,\n"
"      \"clouds\": 90,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.56,\n"
"      \"wind_deg\": 130,\n"
"      \"wind_gust\": 3.78,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682089200,\n"
"      \"temp\": 15.15,\n"
"      \"feels_like\": 14.1,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 53,\n"
"      \"dew_point\": 5.56,\n"
"      \"uvi\": 0.67,\n"
"      \"clouds\": 90,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.84,\n"
"      \"wind_deg\": 113,\n"
"      \"wind_gust\": 3.6,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682092800,\n"
"      \"temp\": 14.77,\n"
"      \"feels_like\": 13.76,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 5.98,\n"
"      \"uvi\": 0.22,\n"
"      \"clouds\": 91,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.48,\n"
"      \"wind_deg\": 95,\n"
"      \"wind_gust\": 2.76,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682096400,\n"
"      \"temp\": 14.06,\n"
"      \"feels_like\": 13.09,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 60,\n"
"      \"dew_point\": 6.4,\n"
"      \"uvi\": 0.06,\n"
"      \"clouds\": 91,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.43,\n"
"      \"wind_deg\": 109,\n"
"      \"wind_gust\": 2.83,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682100000,\n"
"      \"temp\": 12.89,\n"
"      \"feels_like\": 11.93,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 65,\n"
"      \"dew_point\": 6.23,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 88,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.42,\n"
"      \"wind_deg\": 144,\n"
"      \"wind_gust\": 2.08,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682103600,\n"
"      \"temp\": 11.64,\n"
"      \"feels_like\": 10.69,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 6.08,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 25,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.4,\n"
"      \"wind_deg\": 170,\n"
"      \"wind_gust\": 1.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 802,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Mäßig bewölkt\",\n"
"          \"icon\": \"03n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682107200,\n"
"      \"temp\": 10.96,\n"
"      \"feels_like\": 9.97,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 5.83,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 20,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.4,\n"
"      \"wind_deg\": 180,\n"
"      \"wind_gust\": 1.37,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682110800,\n"
"      \"temp\": 10.45,\n"
"      \"feels_like\": 9.43,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 72,\n"
"      \"dew_point\": 5.49,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 18,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.32,\n"
"      \"wind_deg\": 176,\n"
"      \"wind_gust\": 1.34,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682114400,\n"
"      \"temp\": 10.2,\n"
"      \"feels_like\": 9.18,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 73,\n"
"      \"dew_point\": 5.26,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 18,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.22,\n"
"      \"wind_deg\": 169,\n"
"      \"wind_gust\": 1.25,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682118000,\n"
"      \"temp\": 9.89,\n"
"      \"feels_like\": 9.89,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 73,\n"
"      \"dew_point\": 5.02,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 17,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.3,\n"
"      \"wind_deg\": 159,\n"
"      \"wind_gust\": 1.32,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682121600,\n"
"      \"temp\": 9.54,\n"
"      \"feels_like\": 9.29,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 73,\n"
"      \"dew_point\": 4.82,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 18,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.35,\n"
"      \"wind_deg\": 147,\n"
"      \"wind_gust\": 1.41,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682125200,\n"
"      \"temp\": 9.13,\n"
"      \"feels_like\": 9.13,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 74,\n"
"      \"dew_point\": 4.61,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 24,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.25,\n"
"      \"wind_deg\": 146,\n"
"      \"wind_gust\": 1.37,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682128800,\n"
"      \"temp\": 8.7,\n"
"      \"feels_like\": 8.7,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 75,\n"
"      \"dew_point\": 4.39,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 23,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.25,\n"
"      \"wind_deg\": 143,\n"
"      \"wind_gust\": 1.31,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682132400,\n"
"      \"temp\": 8.39,\n"
"      \"feels_like\": 7.93,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 77,\n"
"      \"dew_point\": 4.34,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 21,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.4,\n"
"      \"wind_deg\": 134,\n"
"      \"wind_gust\": 1.39,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682136000,\n"
"      \"temp\": 7.98,\n"
"      \"feels_like\": 7.48,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 79,\n"
"      \"dew_point\": 4.38,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 19,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.39,\n"
"      \"wind_deg\": 142,\n"
"      \"wind_gust\": 1.34,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682139600,\n"
"      \"temp\": 8.77,\n"
"      \"feels_like\": 8.36,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 77,\n"
"      \"dew_point\": 4.78,\n"
"      \"uvi\": 0.2,\n"
"      \"clouds\": 18,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.4,\n"
"      \"wind_deg\": 150,\n"
"      \"wind_gust\": 2.21,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682143200,\n"
"      \"temp\": 10.82,\n"
"      \"feels_like\": 9.76,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 5.15,\n"
"      \"uvi\": 0.66,\n"
"      \"clouds\": 17,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 1.73,\n"
"      \"wind_deg\": 147,\n"
"      \"wind_gust\": 4.69,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682146800,\n"
"      \"temp\": 12.84,\n"
"      \"feels_like\": 11.77,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 61,\n"
"      \"dew_point\": 5.38,\n"
"      \"uvi\": 1.51,\n"
"      \"clouds\": 13,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 2.42,\n"
"      \"wind_deg\": 139,\n"
"      \"wind_gust\": 5.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682150400,\n"
"      \"temp\": 14.73,\n"
"      \"feels_like\": 13.69,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 55,\n"
"      \"dew_point\": 5.53,\n"
"      \"uvi\": 2.66,\n"
"      \"clouds\": 14,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.52,\n"
"      \"wind_deg\": 135,\n"
"      \"wind_gust\": 6.3,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682154000,\n"
"      \"temp\": 16.13,\n"
"      \"feels_like\": 15.08,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 5.26,\n"
"      \"uvi\": 3.83,\n"
"      \"clouds\": 15,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.23,\n"
"      \"wind_deg\": 135,\n"
"      \"wind_gust\": 5.8,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682157600,\n"
"      \"temp\": 17.12,\n"
"      \"feels_like\": 16.06,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 45,\n"
"      \"dew_point\": 5.02,\n"
"      \"uvi\": 4.69,\n"
"      \"clouds\": 13,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.66,\n"
"      \"wind_deg\": 134,\n"
"      \"wind_gust\": 5.79,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682161200,\n"
"      \"temp\": 17.71,\n"
"      \"feels_like\": 16.66,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 43,\n"
"      \"dew_point\": 5.04,\n"
"      \"uvi\": 4.99,\n"
"      \"clouds\": 13,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.79,\n"
"      \"wind_deg\": 134,\n"
"      \"wind_gust\": 5.62,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682164800,\n"
"      \"temp\": 18.23,\n"
"      \"feels_like\": 17.21,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 42,\n"
"      \"dew_point\": 4.92,\n"
"      \"uvi\": 4.61,\n"
"      \"clouds\": 13,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.94,\n"
"      \"wind_deg\": 132,\n"
"      \"wind_gust\": 5.29,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682168400,\n"
"      \"temp\": 18.35,\n"
"      \"feels_like\": 17.34,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 42,\n"
"      \"dew_point\": 5.02,\n"
"      \"uvi\": 3.69,\n"
"      \"clouds\": 19,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.18,\n"
"      \"wind_deg\": 128,\n"
"      \"wind_gust\": 5.3,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682172000,\n"
"      \"temp\": 18.01,\n"
"      \"feels_like\": 17.02,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 44,\n"
"      \"dew_point\": 5.31,\n"
"      \"uvi\": 2.5,\n"
"      \"clouds\": 20,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.37,\n"
"      \"wind_deg\": 125,\n"
"      \"wind_gust\": 5.84,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682175600,\n"
"      \"temp\": 17.4,\n"
"      \"feels_like\": 16.42,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 47,\n"
"      \"dew_point\": 5.79,\n"
"      \"uvi\": 1.39,\n"
"      \"clouds\": 20,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.31,\n"
"      \"wind_deg\": 126,\n"
"      \"wind_gust\": 6.45,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682179200,\n"
"      \"temp\": 16.64,\n"
"      \"feels_like\": 15.69,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 51,\n"
"      \"dew_point\": 6.32,\n"
"      \"uvi\": 0.59,\n"
"      \"clouds\": 16,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.89,\n"
"      \"wind_deg\": 127,\n"
"      \"wind_gust\": 7.05,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1682182800,\n"
"      \"temp\": 15.23,\n"
"      \"feels_like\": 14.3,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 57,\n"
"      \"dew_point\": 6.73,\n"
"      \"uvi\": 0.16,\n"
"      \"clouds\": 12,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.42,\n"
"      \"wind_deg\": 127,\n"
"      \"wind_gust\": 8.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    }\n"
"  ],\n"
"  \"daily\": [\n"
"    {\n"
"      \"dt\": 1681984800,\n"
"      \"sunrise\": 1681962968,\n"
"      \"sunset\": 1682013053,\n"
"      \"moonrise\": 1681963440,\n"
"      \"moonset\": 1682015340,\n"
"      \"moon_phase\": 0,\n"
"      \"temp\": {\n"
"        \"day\": 11.53,\n"
"        \"min\": 4.58,\n"
"        \"max\": 15.6,\n"
"        \"night\": 11.72,\n"
"        \"eve\": 13.94,\n"
"        \"morn\": 4.58\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 10.51,\n"
"        \"night\": 10.93,\n"
"        \"eve\": 13.11,\n"
"        \"morn\": 3.52\n"
"      },\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 5.62,\n"
"      \"wind_speed\": 4.1,\n"
"      \"wind_deg\": 127,\n"
"      \"wind_gust\": 6.46,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.03,\n"
"      \"uvi\": 3.42\n"
"    },\n"
"    {\n"
"      \"dt\": 1682071200,\n"
"      \"sunrise\": 1682049256,\n"
"      \"sunset\": 1682099540,\n"
"      \"moonrise\": 1682051040,\n"
"      \"moonset\": 1682106480,\n"
"      \"moon_phase\": 0.04,\n"
"      \"temp\": {\n"
"        \"day\": 15.85,\n"
"        \"min\": 8.84,\n"
"        \"max\": 16.81,\n"
"        \"night\": 10.45,\n"
"        \"eve\": 14.77,\n"
"        \"morn\": 8.84\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 14.77,\n"
"        \"night\": 9.43,\n"
"        \"eve\": 13.76,\n"
"        \"morn\": 7.72\n"
"      },\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 4.96,\n"
"      \"wind_speed\": 4.66,\n"
"      \"wind_deg\": 133,\n"
"      \"wind_gust\": 7.8,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 9,\n"
"      \"pop\": 0.01,\n"
"      \"uvi\": 4.68\n"
"    },\n"
"    {\n"
"      \"dt\": 1682157600,\n"
"      \"sunrise\": 1682135546,\n"
"      \"sunset\": 1682186028,\n"
"      \"moonrise\": 1682138880,\n"
"      \"moonset\": 1682197500,\n"
"      \"moon_phase\": 0.08,\n"
"      \"temp\": {\n"
"        \"day\": 17.12,\n"
"        \"min\": 7.98,\n"
"        \"max\": 18.35,\n"
"        \"night\": 11.84,\n"
"        \"eve\": 16.64,\n"
"        \"morn\": 7.98\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 16.06,\n"
"        \"night\": 10.86,\n"
"        \"eve\": 15.69,\n"
"        \"morn\": 7.48\n"
"      },\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 45,\n"
"      \"dew_point\": 5.02,\n"
"      \"wind_speed\": 5.37,\n"
"      \"wind_deg\": 125,\n"
"      \"wind_gust\": 10.84,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 13,\n"
"      \"pop\": 0,\n"
"      \"uvi\": 4.99\n"
"    },\n"
"    {\n"
"      \"dt\": 1682244000,\n"
"      \"sunrise\": 1682221836,\n"
"      \"sunset\": 1682272515,\n"
"      \"moonrise\": 1682227080,\n"
"      \"moonset\": 0,\n"
"      \"moon_phase\": 0.11,\n"
"      \"temp\": {\n"
"        \"day\": 18.04,\n"
"        \"min\": 7.8,\n"
"        \"max\": 19.09,\n"
"        \"night\": 13.05,\n"
"        \"eve\": 18.24,\n"
"        \"morn\": 7.8\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 17.07,\n"
"        \"night\": 12.37,\n"
"        \"eve\": 17.43,\n"
"        \"morn\": 7.8\n"
"      },\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 45,\n"
"      \"dew_point\": 5.73,\n"
"      \"wind_speed\": 5.17,\n"
"      \"wind_deg\": 140,\n"
"      \"wind_gust\": 10.71,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 8,\n"
"      \"pop\": 0.22,\n"
"      \"uvi\": 5.14\n"
"    },\n"
"    {\n"
"      \"dt\": 1682330400,\n"
"      \"sunrise\": 1682308128,\n"
"      \"sunset\": 1682359002,\n"
"      \"moonrise\": 1682315760,\n"
"      \"moonset\": 1682288160,\n"
"      \"moon_phase\": 0.14,\n"
"      \"temp\": {\n"
"        \"day\": 11.05,\n"
"        \"min\": 10.48,\n"
"        \"max\": 15.43,\n"
"        \"night\": 10.65,\n"
"        \"eve\": 14.76,\n"
"        \"morn\": 12.18\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 10.46,\n"
"        \"night\": 9.73,\n"
"        \"eve\": 13.88,\n"
"        \"morn\": 11.52\n"
"      },\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 8.62,\n"
"      \"wind_speed\": 5.55,\n"
"      \"wind_deg\": 288,\n"
"      \"wind_gust\": 11.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.92,\n"
"      \"rain\": 3.91,\n"
"      \"uvi\": 3.18\n"
"    },\n"
"    {\n"
"      \"dt\": 1682416800,\n"
"      \"sunrise\": 1682394420,\n"
"      \"sunset\": 1682445489,\n"
"      \"moonrise\": 1682405100,\n"
"      \"moonset\": 1682378280,\n"
"      \"moon_phase\": 0.17,\n"
"      \"temp\": {\n"
"        \"day\": 14.7,\n"
"        \"min\": 7.5,\n"
"        \"max\": 17.88,\n"
"        \"night\": 8.4,\n"
"        \"eve\": 15.18,\n"
"        \"morn\": 7.5\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 13.45,\n"
"        \"night\": 4.98,\n"
"        \"eve\": 14.4,\n"
"        \"morn\": 5.71\n"
"      },\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 47,\n"
"      \"dew_point\": 3.39,\n"
"      \"wind_speed\": 6.68,\n"
"      \"wind_deg\": 294,\n"
"      \"wind_gust\": 13.82,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 501,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Mäßiger Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 99,\n"
"      \"pop\": 1,\n"
"      \"rain\": 9.64,\n"
"      \"uvi\": 5.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1682503200,\n"
"      \"sunrise\": 1682480714,\n"
"      \"sunset\": 1682531976,\n"
"      \"moonrise\": 1682494980,\n"
"      \"moonset\": 1682467680,\n"
"      \"moon_phase\": 0.21,\n"
"      \"temp\": {\n"
"        \"day\": 9.5,\n"
"        \"min\": 5.46,\n"
"        \"max\": 12.23,\n"
"        \"night\": 7.83,\n"
"        \"eve\": 12.23,\n"
"        \"morn\": 5.46\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 6.14,\n"
"        \"night\": 6.79,\n"
"        \"eve\": 10.47,\n"
"        \"morn\": 1.32\n"
"      },\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 43,\n"
"      \"dew_point\": -2.68,\n"
"      \"wind_speed\": 7.68,\n"
"      \"wind_deg\": 300,\n"
"      \"wind_gust\": 13.92,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 21,\n"
"      \"pop\": 0.35,\n"
"      \"rain\": 0.28,\n"
"      \"uvi\": 6\n"
"    },\n"
"    {\n"
"      \"dt\": 1682589600,\n"
"      \"sunrise\": 1682567009,\n"
"      \"sunset\": 1682618463,\n"
"      \"moonrise\": 1682585280,\n"
"      \"moonset\": 1682556420,\n"
"      \"moon_phase\": 0.25,\n"
"      \"temp\": {\n"
"        \"day\": 12.19,\n"
"        \"min\": 4.26,\n"
"        \"max\": 14.99,\n"
"        \"night\": 8.71,\n"
"        \"eve\": 14.99,\n"
"        \"morn\": 4.26\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 10.67,\n"
"        \"night\": 8.71,\n"
"        \"eve\": 13.59,\n"
"        \"morn\": 4.26\n"
"      },\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 46,\n"
"      \"dew_point\": 0.76,\n"
"      \"wind_speed\": 1.71,\n"
"      \"wind_deg\": 135,\n"
"      \"wind_gust\": 4.03,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 801,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Ein paar Wolken\",\n"
"          \"icon\": \"02d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 11,\n"
"      \"pop\": 0,\n"
"      \"uvi\": 6\n"
"    }\n"
"  ]\n"
"}";