#include <Arduino.h>

String json_test = "{\n"
"  \"lat\": 48.2141,\n"
"  \"lon\": 16.3232,\n"
"  \"timezone\": \"Europe/Vienna\",\n"
"  \"timezone_offset\": 7200,\n"
"  \"current\": {\n"
"    \"dt\": 1680295786,\n"
"    \"sunrise\": 1680237349,\n"
"    \"sunset\": 1680283314,\n"
"    \"temp\": 11.68,\n"
"    \"feels_like\": 10.68,\n"
"    \"pressure\": 1004,\n"
"    \"humidity\": 68,\n"
"    \"dew_point\": 5.98,\n"
"    \"uvi\": 0,\n"
"    \"clouds\": 75,\n"
"    \"visibility\": 10000,\n"
"    \"wind_speed\": 3.09,\n"
"    \"wind_deg\": 250,\n"
"    \"weather\": [\n"
"      {\n"
"        \"id\": 803,\n"
"        \"main\": \"Clouds\",\n"
"        \"description\": \"Überwiegend bewölkt\",\n"
"        \"icon\": \"04n\"\n"
"      }\n"
"    ]\n"
"  },\n"
"  \"minutely\": [\n"
"    {\n"
"      \"dt\": 1680295800,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680295860,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680295920,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680295980,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296400,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296460,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296520,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296580,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296640,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296700,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296760,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296820,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296880,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296940,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297000,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297060,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297120,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297180,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297240,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297300,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297360,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297420,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297480,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297540,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297600,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297660,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297720,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297780,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297840,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297900,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680297960,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298020,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298080,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298140,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298200,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298260,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298320,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298380,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298440,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298500,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298560,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298620,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298680,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298740,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298800,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298860,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298920,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680298980,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299040,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299100,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299160,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299220,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299280,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299340,\n"
"      \"precipitation\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680299400,\n"
"      \"precipitation\": 0\n"
"    }\n"
"  ],\n"
"  \"hourly\": [\n"
"    {\n"
"      \"dt\": 1680292800,\n"
"      \"temp\": 11.64,\n"
"      \"feels_like\": 10.61,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 5.73,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.59,\n"
"      \"wind_deg\": 265,\n"
"      \"wind_gust\": 11.65,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.24,\n"
"      \"rain\": {\n"
"        \"1h\": 0.12\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680296400,\n"
"      \"temp\": 11.68,\n"
"      \"feels_like\": 10.68,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 5.98,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 75,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.1,\n"
"      \"wind_deg\": 267,\n"
"      \"wind_gust\": 12.46,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.04\n"
"    },\n"
"    {\n"
"      \"dt\": 1680300000,\n"
"      \"temp\": 11.61,\n"
"      \"feels_like\": 10.58,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 5.7,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.84,\n"
"      \"wind_deg\": 270,\n"
"      \"wind_gust\": 12.78,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1680303600,\n"
"      \"temp\": 11.31,\n"
"      \"feels_like\": 10.27,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 5.63,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 85,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.44,\n"
"      \"wind_deg\": 269,\n"
"      \"wind_gust\": 12.94,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1680307200,\n"
"      \"temp\": 11.15,\n"
"      \"feels_like\": 10.07,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 5.26,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 90,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.61,\n"
"      \"wind_deg\": 276,\n"
"      \"wind_gust\": 13.07,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1680310800,\n"
"      \"temp\": 10.62,\n"
"      \"feels_like\": 9.59,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 5.59,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 95,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.89,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 13.08,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680314400,\n"
"      \"temp\": 10.08,\n"
"      \"feels_like\": 9,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 4.85,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.22,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 12.72,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680318000,\n"
"      \"temp\": 9.56,\n"
"      \"feels_like\": 6.54,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 72,\n"
"      \"dew_point\": 4.61,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.44,\n"
"      \"wind_deg\": 277,\n"
"      \"wind_gust\": 12.62,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680321600,\n"
"      \"temp\": 9.78,\n"
"      \"feels_like\": 6.93,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 4.19,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.1,\n"
"      \"wind_deg\": 279,\n"
"      \"wind_gust\": 12.87,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680325200,\n"
"      \"temp\": 9.55,\n"
"      \"feels_like\": 6.53,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 3.76,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.43,\n"
"      \"wind_deg\": 282,\n"
"      \"wind_gust\": 13.85,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680328800,\n"
"      \"temp\": 9.59,\n"
"      \"feels_like\": 6.5,\n"
"      \"pressure\": 1003,\n"
"      \"humidity\": 69,\n"
"      \"dew_point\": 4,\n"
"      \"uvi\": 0.26,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.69,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 13.7,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680332400,\n"
"      \"temp\": 10.06,\n"
"      \"feels_like\": 8.87,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 67,\n"
"      \"dew_point\": 4.04,\n"
"      \"uvi\": 0.78,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.87,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 14.09,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680336000,\n"
"      \"temp\": 10.23,\n"
"      \"feels_like\": 9.08,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 4.37,\n"
"      \"uvi\": 1.49,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.78,\n"
"      \"wind_deg\": 282,\n"
"      \"wind_gust\": 12.72,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680339600,\n"
"      \"temp\": 11.84,\n"
"      \"feels_like\": 10.62,\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 59,\n"
"      \"dew_point\": 3.98,\n"
"      \"uvi\": 2.27,\n"
"      \"clouds\": 88,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.31,\n"
"      \"wind_deg\": 283,\n"
"      \"wind_gust\": 12.22,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680343200,\n"
"      \"temp\": 12.87,\n"
"      \"feels_like\": 11.62,\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 54,\n"
"      \"dew_point\": 3.45,\n"
"      \"uvi\": 2.79,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.67,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 11.96,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680346800,\n"
"      \"temp\": 12.47,\n"
"      \"feels_like\": 11.23,\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 56,\n"
"      \"dew_point\": 3.72,\n"
"      \"uvi\": 2.98,\n"
"      \"clouds\": 84,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 7.88,\n"
"      \"wind_deg\": 283,\n"
"      \"wind_gust\": 11.68,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.02\n"
"    },\n"
"    {\n"
"      \"dt\": 1680350400,\n"
"      \"temp\": 13.02,\n"
"      \"feels_like\": 11.68,\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 50,\n"
"      \"dew_point\": 2.72,\n"
"      \"uvi\": 2.73,\n"
"      \"clouds\": 80,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.91,\n"
"      \"wind_deg\": 291,\n"
"      \"wind_gust\": 10.76,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.02\n"
"    },\n"
"    {\n"
"      \"dt\": 1680354000,\n"
"      \"temp\": 14.34,\n"
"      \"feels_like\": 12.93,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 42,\n"
"      \"dew_point\": 1.62,\n"
"      \"uvi\": 2.02,\n"
"      \"clouds\": 33,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.98,\n"
"      \"wind_deg\": 299,\n"
"      \"wind_gust\": 10.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 802,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Mäßig bewölkt\",\n"
"          \"icon\": \"03d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680357600,\n"
"      \"temp\": 14.37,\n"
"      \"feels_like\": 12.99,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 43,\n"
"      \"dew_point\": 1.82,\n"
"      \"uvi\": 1.29,\n"
"      \"clouds\": 56,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.32,\n"
"      \"wind_deg\": 295,\n"
"      \"wind_gust\": 9.99,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680361200,\n"
"      \"temp\": 13.56,\n"
"      \"feels_like\": 12.25,\n"
"      \"pressure\": 1004,\n"
"      \"humidity\": 49,\n"
"      \"dew_point\": 2.74,\n"
"      \"uvi\": 0.65,\n"
"      \"clouds\": 69,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.32,\n"
"      \"wind_deg\": 299,\n"
"      \"wind_gust\": 9.51,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.06\n"
"    },\n"
"    {\n"
"      \"dt\": 1680364800,\n"
"      \"temp\": 12.47,\n"
"      \"feels_like\": 11.31,\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 59,\n"
"      \"dew_point\": 4.33,\n"
"      \"uvi\": 0.28,\n"
"      \"clouds\": 67,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.79,\n"
"      \"wind_deg\": 292,\n"
"      \"wind_gust\": 10.68,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.32,\n"
"      \"rain\": {\n"
"        \"1h\": 0.22\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680368400,\n"
"      \"temp\": 10.44,\n"
"      \"feels_like\": 9.32,\n"
"      \"pressure\": 1007,\n"
"      \"humidity\": 68,\n"
"      \"dew_point\": 4.64,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 67,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 6.15,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 11.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.1\n"
"    },\n"
"    {\n"
"      \"dt\": 1680372000,\n"
"      \"temp\": 9.83,\n"
"      \"feels_like\": 7.07,\n"
"      \"pressure\": 1007,\n"
"      \"humidity\": 70,\n"
"      \"dew_point\": 4.43,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 68,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.88,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 11.77,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 803,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Überwiegend bewölkt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.1\n"
"    },\n"
"    {\n"
"      \"dt\": 1680375600,\n"
"      \"temp\": 9.46,\n"
"      \"feels_like\": 6.61,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 71,\n"
"      \"dew_point\": 4.29,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 87,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.83,\n"
"      \"wind_deg\": 286,\n"
"      \"wind_gust\": 11.72,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680379200,\n"
"      \"temp\": 9.33,\n"
"      \"feels_like\": 6.55,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 73,\n"
"      \"dew_point\": 4.6,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 93,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.53,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 11.49,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1680382800,\n"
"      \"temp\": 9.1,\n"
"      \"feels_like\": 6.24,\n"
"      \"pressure\": 1008,\n"
"      \"humidity\": 75,\n"
"      \"dew_point\": 4.71,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 96,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.61,\n"
"      \"wind_deg\": 281,\n"
"      \"wind_gust\": 10.95,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.03\n"
"    },\n"
"    {\n"
"      \"dt\": 1680386400,\n"
"      \"temp\": 8.78,\n"
"      \"feels_like\": 5.91,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 4.91,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 5.4,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 10.08,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0\n"
"    },\n"
"    {\n"
"      \"dt\": 1680390000,\n"
"      \"temp\": 8.52,\n"
"      \"feels_like\": 5.84,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 5.22,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 97,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.76,\n"
"      \"wind_deg\": 288,\n"
"      \"wind_gust\": 9.56,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.32,\n"
"      \"rain\": {\n"
"        \"1h\": 0.28\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680393600,\n"
"      \"temp\": 8.38,\n"
"      \"feels_like\": 5.9,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 5.5,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.24,\n"
"      \"wind_deg\": 293,\n"
"      \"wind_gust\": 9.25,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.39,\n"
"      \"rain\": {\n"
"        \"1h\": 0.29\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680397200,\n"
"      \"temp\": 8.51,\n"
"      \"feels_like\": 6.47,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 82,\n"
"      \"dew_point\": 5.38,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.43,\n"
"      \"wind_deg\": 294,\n"
"      \"wind_gust\": 8.56,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.27\n"
"    },\n"
"    {\n"
"      \"dt\": 1680400800,\n"
"      \"temp\": 8.53,\n"
"      \"feels_like\": 6.5,\n"
"      \"pressure\": 1009,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 5.24,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.42,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 7.9,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.07\n"
"    },\n"
"    {\n"
"      \"dt\": 1680404400,\n"
"      \"temp\": 8.59,\n"
"      \"feels_like\": 6.49,\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 80,\n"
"      \"dew_point\": 5.13,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.56,\n"
"      \"wind_deg\": 285,\n"
"      \"wind_gust\": 8.06,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.01\n"
"    },\n"
"    {\n"
"      \"dt\": 1680408000,\n"
"      \"temp\": 8.4,\n"
"      \"feels_like\": 5.99,\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 5.19,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.09,\n"
"      \"wind_deg\": 280,\n"
"      \"wind_gust\": 8.18,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.32,\n"
"      \"rain\": {\n"
"        \"1h\": 0.16\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680411600,\n"
"      \"temp\": 8.34,\n"
"      \"feels_like\": 5.78,\n"
"      \"pressure\": 1010,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 5.12,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.38,\n"
"      \"wind_deg\": 285,\n"
"      \"wind_gust\": 8.19,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.26,\n"
"      \"rain\": {\n"
"        \"1h\": 0.11\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680415200,\n"
"      \"temp\": 8.14,\n"
"      \"feels_like\": 5.67,\n"
"      \"pressure\": 1011,\n"
"      \"humidity\": 83,\n"
"      \"dew_point\": 5.21,\n"
"      \"uvi\": 0.04,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.09,\n"
"      \"wind_deg\": 287,\n"
"      \"wind_gust\": 8.12,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.37,\n"
"      \"rain\": {\n"
"        \"1h\": 0.27\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680418800,\n"
"      \"temp\": 8.58,\n"
"      \"feels_like\": 6.37,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 80,\n"
"      \"dew_point\": 5.12,\n"
"      \"uvi\": 0.14,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.77,\n"
"      \"wind_deg\": 291,\n"
"      \"wind_gust\": 7.74,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.45,\n"
"      \"rain\": {\n"
"        \"1h\": 0.23\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680422400,\n"
"      \"temp\": 8.95,\n"
"      \"feels_like\": 6.77,\n"
"      \"pressure\": 1012,\n"
"      \"humidity\": 78,\n"
"      \"dew_point\": 5.1,\n"
"      \"uvi\": 0.26,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.87,\n"
"      \"wind_deg\": 301,\n"
"      \"wind_gust\": 7.54,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.48,\n"
"      \"rain\": {\n"
"        \"1h\": 0.21\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680426000,\n"
"      \"temp\": 8.72,\n"
"      \"feels_like\": 6.63,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 81,\n"
"      \"dew_point\": 5.47,\n"
"      \"uvi\": 0.39,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.61,\n"
"      \"wind_deg\": 304,\n"
"      \"wind_gust\": 7.2,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.53,\n"
"      \"rain\": {\n"
"        \"1h\": 0.41\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680429600,\n"
"      \"temp\": 8.61,\n"
"      \"feels_like\": 6.62,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 84,\n"
"      \"dew_point\": 5.85,\n"
"      \"uvi\": 0.3,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.38,\n"
"      \"wind_deg\": 306,\n"
"      \"wind_gust\": 7.23,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.53,\n"
"      \"rain\": {\n"
"        \"1h\": 0.7\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680433200,\n"
"      \"temp\": 8.5,\n"
"      \"feels_like\": 6.27,\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 85,\n"
"      \"dew_point\": 6.03,\n"
"      \"uvi\": 0.32,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.78,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 7.04,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.61,\n"
"      \"rain\": {\n"
"        \"1h\": 0.54\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680436800,\n"
"      \"temp\": 8.47,\n"
"      \"feels_like\": 6.18,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 6.08,\n"
"      \"uvi\": 0.3,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.89,\n"
"      \"wind_deg\": 303,\n"
"      \"wind_gust\": 7.47,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.65,\n"
"      \"rain\": {\n"
"        \"1h\": 0.44\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680440400,\n"
"      \"temp\": 8.34,\n"
"      \"feels_like\": 5.94,\n"
"      \"pressure\": 1014,\n"
"      \"humidity\": 87,\n"
"      \"dew_point\": 6.1,\n"
"      \"uvi\": 0.51,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.04,\n"
"      \"wind_deg\": 310,\n"
"      \"wind_gust\": 7.88,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.64,\n"
"      \"rain\": {\n"
"        \"1h\": 0.47\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680444000,\n"
"      \"temp\": 8.41,\n"
"      \"feels_like\": 6.21,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 5.95,\n"
"      \"uvi\": 0.33,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.68,\n"
"      \"wind_deg\": 315,\n"
"      \"wind_gust\": 7.15,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.61,\n"
"      \"rain\": {\n"
"        \"1h\": 0.21\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680447600,\n"
"      \"temp\": 8.27,\n"
"      \"feels_like\": 6.05,\n"
"      \"pressure\": 1015,\n"
"      \"humidity\": 86,\n"
"      \"dew_point\": 5.96,\n"
"      \"uvi\": 0.17,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.67,\n"
"      \"wind_deg\": 344,\n"
"      \"wind_gust\": 6.9,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.56,\n"
"      \"rain\": {\n"
"        \"1h\": 0.26\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680451200,\n"
"      \"temp\": 6.95,\n"
"      \"feels_like\": 4.35,\n"
"      \"pressure\": 1016,\n"
"      \"humidity\": 87,\n"
"      \"dew_point\": 4.69,\n"
"      \"uvi\": 0.03,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 3.83,\n"
"      \"wind_deg\": 14,\n"
"      \"wind_gust\": 8.43,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.64,\n"
"      \"rain\": {\n"
"        \"1h\": 0.47\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680454800,\n"
"      \"temp\": 5.8,\n"
"      \"feels_like\": 2.5,\n"
"      \"pressure\": 1017,\n"
"      \"humidity\": 85,\n"
"      \"dew_point\": 3.33,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.66,\n"
"      \"wind_deg\": 13,\n"
"      \"wind_gust\": 10.69,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.64,\n"
"      \"rain\": {\n"
"        \"1h\": 0.18\n"
"      }\n"
"    },\n"
"    {\n"
"      \"dt\": 1680458400,\n"
"      \"temp\": 5.02,\n"
"      \"feels_like\": 1.57,\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 84,\n"
"      \"dew_point\": 2.33,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 100,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.57,\n"
"      \"wind_deg\": 10,\n"
"      \"wind_gust\": 11.44,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.64\n"
"    },\n"
"    {\n"
"      \"dt\": 1680462000,\n"
"      \"temp\": 4.85,\n"
"      \"feels_like\": 1.29,\n"
"      \"pressure\": 1020,\n"
"      \"humidity\": 80,\n"
"      \"dew_point\": 1.51,\n"
"      \"uvi\": 0,\n"
"      \"clouds\": 98,\n"
"      \"visibility\": 10000,\n"
"      \"wind_speed\": 4.71,\n"
"      \"wind_deg\": 8,\n"
"      \"wind_gust\": 11.37,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 804,\n"
"          \"main\": \"Clouds\",\n"
"          \"description\": \"Bedeckt\",\n"
"          \"icon\": \"04n\"\n"
"        }\n"
"      ],\n"
"      \"pop\": 0.2\n"
"    }\n"
"  ],\n"
"  \"daily\": [\n"
"    {\n"
"      \"dt\": 1680256800,\n"
"      \"sunrise\": 1680237349,\n"
"      \"sunset\": 1680283314,\n"
"      \"moonrise\": 1680260580,\n"
"      \"moonset\": 1680230880,\n"
"      \"moon_phase\": 0.32,\n"
"      \"temp\": {\n"
"        \"day\": 16.21,\n"
"        \"min\": 8.28,\n"
"        \"max\": 19.35,\n"
"        \"night\": 11.68,\n"
"        \"eve\": 14.68,\n"
"        \"morn\": 8.28\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 15.04,\n"
"        \"night\": 10.68,\n"
"        \"eve\": 13.61,\n"
"        \"morn\": 7.13\n"
"      },\n"
"      \"pressure\": 1006,\n"
"      \"humidity\": 44,\n"
"      \"dew_point\": 3.96,\n"
"      \"wind_speed\": 6.69,\n"
"      \"wind_deg\": 265,\n"
"      \"wind_gust\": 15.14,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.3,\n"
"      \"rain\": 0.12,\n"
"      \"uvi\": 2.8\n"
"    },\n"
"    {\n"
"      \"dt\": 1680343200,\n"
"      \"sunrise\": 1680323625,\n"
"      \"sunset\": 1680369801,\n"
"      \"moonrise\": 1680351120,\n"
"      \"moonset\": 1680318900,\n"
"      \"moon_phase\": 0.35,\n"
"      \"temp\": {\n"
"        \"day\": 12.87,\n"
"        \"min\": 9.1,\n"
"        \"max\": 14.37,\n"
"        \"night\": 9.1,\n"
"        \"eve\": 12.47,\n"
"        \"morn\": 9.78\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 11.62,\n"
"        \"night\": 6.24,\n"
"        \"eve\": 11.31,\n"
"        \"morn\": 6.93\n"
"      },\n"
"      \"pressure\": 1005,\n"
"      \"humidity\": 54,\n"
"      \"dew_point\": 3.45,\n"
"      \"wind_speed\": 7.88,\n"
"      \"wind_deg\": 283,\n"
"      \"wind_gust\": 14.09,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 84,\n"
"      \"pop\": 0.32,\n"
"      \"rain\": 0.22,\n"
"      \"uvi\": 2.98\n"
"    },\n"
"    {\n"
"      \"dt\": 1680429600,\n"
"      \"sunrise\": 1680409901,\n"
"      \"sunset\": 1680456288,\n"
"      \"moonrise\": 1680441660,\n"
"      \"moonset\": 1680406560,\n"
"      \"moon_phase\": 0.38,\n"
"      \"temp\": {\n"
"        \"day\": 8.61,\n"
"        \"min\": 4.06,\n"
"        \"max\": 8.95,\n"
"        \"night\": 4.06,\n"
"        \"eve\": 6.95,\n"
"        \"morn\": 8.4\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 6.62,\n"
"        \"night\": 0.29,\n"
"        \"eve\": 4.35,\n"
"        \"morn\": 5.99\n"
"      },\n"
"      \"pressure\": 1013,\n"
"      \"humidity\": 84,\n"
"      \"dew_point\": 5.85,\n"
"      \"wind_speed\": 5.4,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 11.44,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.65,\n"
"      \"rain\": 5.23,\n"
"      \"uvi\": 0.51\n"
"    },\n"
"    {\n"
"      \"dt\": 1680516000,\n"
"      \"sunrise\": 1680496178,\n"
"      \"sunset\": 1680542775,\n"
"      \"moonrise\": 1680532200,\n"
"      \"moonset\": 1680493980,\n"
"      \"moon_phase\": 0.41,\n"
"      \"temp\": {\n"
"        \"day\": 5.49,\n"
"        \"min\": 2.05,\n"
"        \"max\": 7.66,\n"
"        \"night\": 2.73,\n"
"        \"eve\": 7.66,\n"
"        \"morn\": 2.9\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 1.33,\n"
"        \"night\": -0.68,\n"
"        \"eve\": 4.29,\n"
"        \"morn\": -1.52\n"
"      },\n"
"      \"pressure\": 1025,\n"
"      \"humidity\": 36,\n"
"      \"dew_point\": -8.39,\n"
"      \"wind_speed\": 6.53,\n"
"      \"wind_deg\": 356,\n"
"      \"wind_gust\": 10.57,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 4,\n"
"      \"pop\": 0.23,\n"
"      \"uvi\": 4\n"
"    },\n"
"    {\n"
"      \"dt\": 1680602400,\n"
"      \"sunrise\": 1680582455,\n"
"      \"sunset\": 1680629261,\n"
"      \"moonrise\": 1680622740,\n"
"      \"moonset\": 1680581280,\n"
"      \"moon_phase\": 0.44,\n"
"      \"temp\": {\n"
"        \"day\": 2.97,\n"
"        \"min\": 0.09,\n"
"        \"max\": 5.55,\n"
"        \"night\": 0.61,\n"
"        \"eve\": 5.55,\n"
"        \"morn\": 0.09\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": -1.48,\n"
"        \"night\": -2.41,\n"
"        \"eve\": 1.59,\n"
"        \"morn\": -4.28\n"
"      },\n"
"      \"pressure\": 1022,\n"
"      \"humidity\": 46,\n"
"      \"dew_point\": -7.85,\n"
"      \"wind_speed\": 6,\n"
"      \"wind_deg\": 342,\n"
"      \"wind_gust\": 10.01,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 600,\n"
"          \"main\": \"Snow\",\n"
"          \"description\": \"Mäßiger Schnee\",\n"
"          \"icon\": \"13d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 90,\n"
"      \"pop\": 0.34,\n"
"      \"snow\": 0.13,\n"
"      \"uvi\": 3.1\n"
"    },\n"
"    {\n"
"      \"dt\": 1680688800,\n"
"      \"sunrise\": 1680668733,\n"
"      \"sunset\": 1680715748,\n"
"      \"moonrise\": 1680713340,\n"
"      \"moonset\": 1680668520,\n"
"      \"moon_phase\": 0.47,\n"
"      \"temp\": {\n"
"        \"day\": 4.75,\n"
"        \"min\": -0.32,\n"
"        \"max\": 7.37,\n"
"        \"night\": 2.69,\n"
"        \"eve\": 7.37,\n"
"        \"morn\": 0.33\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 2.27,\n"
"        \"night\": 1.17,\n"
"        \"eve\": 5.99,\n"
"        \"morn\": -3.12\n"
"      },\n"
"      \"pressure\": 1019,\n"
"      \"humidity\": 46,\n"
"      \"dew_point\": -5.98,\n"
"      \"wind_speed\": 3.36,\n"
"      \"wind_deg\": 284,\n"
"      \"wind_gust\": 7.12,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 500,\n"
"          \"main\": \"Rain\",\n"
"          \"description\": \"Leichter Regen\",\n"
"          \"icon\": \"10d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 62,\n"
"      \"pop\": 0.33,\n"
"      \"rain\": 0.17,\n"
"      \"uvi\": 3.23\n"
"    },\n"
"    {\n"
"      \"dt\": 1680775200,\n"
"      \"sunrise\": 1680755011,\n"
"      \"sunset\": 1680802235,\n"
"      \"moonrise\": 1680804060,\n"
"      \"moonset\": 1680755820,\n"
"      \"moon_phase\": 0.5,\n"
"      \"temp\": {\n"
"        \"day\": 6.01,\n"
"        \"min\": -0.05,\n"
"        \"max\": 9.71,\n"
"        \"night\": 3.92,\n"
"        \"eve\": 9.71,\n"
"        \"morn\": -0.05\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 3.71,\n"
"        \"night\": 1.06,\n"
"        \"eve\": 7.55,\n"
"        \"morn\": -1.98\n"
"      },\n"
"      \"pressure\": 1021,\n"
"      \"humidity\": 42,\n"
"      \"dew_point\": -6.16,\n"
"      \"wind_speed\": 4.22,\n"
"      \"wind_deg\": 339,\n"
"      \"wind_gust\": 8.24,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 800,\n"
"          \"main\": \"Clear\",\n"
"          \"description\": \"Klarer Himmel\",\n"
"          \"icon\": \"01d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 7,\n"
"      \"pop\": 0,\n"
"      \"uvi\": 4\n"
"    },\n"
"    {\n"
"      \"dt\": 1680861600,\n"
"      \"sunrise\": 1680841289,\n"
"      \"sunset\": 1680888721,\n"
"      \"moonrise\": 1680894960,\n"
"      \"moonset\": 1680843180,\n"
"      \"moon_phase\": 0.54,\n"
"      \"temp\": {\n"
"        \"day\": 2.97,\n"
"        \"min\": 2.09,\n"
"        \"max\": 3.78,\n"
"        \"night\": 3.18,\n"
"        \"eve\": 3.77,\n"
"        \"morn\": 2.22\n"
"      },\n"
"      \"feels_like\": {\n"
"        \"day\": 0.03,\n"
"        \"night\": 1.6,\n"
"        \"eve\": 1.75,\n"
"        \"morn\": -1.38\n"
"      },\n"
"      \"pressure\": 1020,\n"
"      \"humidity\": 94,\n"
"      \"dew_point\": 1.8,\n"
"      \"wind_speed\": 3.79,\n"
"      \"wind_deg\": 297,\n"
"      \"wind_gust\": 9.93,\n"
"      \"weather\": [\n"
"        {\n"
"          \"id\": 616,\n"
"          \"main\": \"Snow\",\n"
"          \"description\": \"Regen und Schnee\",\n"
"          \"icon\": \"13d\"\n"
"        }\n"
"      ],\n"
"      \"clouds\": 100,\n"
"      \"pop\": 0.64,\n"
"      \"rain\": 0.31,\n"
"      \"snow\": 1.53,\n"
"      \"uvi\": 4\n"
"    }\n"
"  ]\n"
"}";