// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SetupScreen
void ui_SetupScreen_screen_init(void);
void ui_event_SetupScreen( lv_event_t * e);
lv_obj_t *ui_SetupScreen;
lv_obj_t *ui_PanelSetup;
lv_obj_t *ui_PanelNetworks;
lv_obj_t *ui_LabelNetworks;
lv_obj_t *ui_DropdownNetworks;
void ui_event_ButtonScan( lv_event_t * e);
lv_obj_t *ui_ButtonScan;
lv_obj_t *ui_LabelScan;
lv_obj_t *ui_PanelPassword;
lv_obj_t *ui_LabelPassword;
void ui_event_TextAreaPassword( lv_event_t * e);
lv_obj_t *ui_TextAreaPassword;
void ui_event_ButtonConnect( lv_event_t * e);
lv_obj_t *ui_ButtonConnect;
lv_obj_t *ui_LabelScan1;
lv_obj_t *ui_PanelAppId;
lv_obj_t *ui_LabelAppId;
void ui_event_TextAreaAppId( lv_event_t * e);
lv_obj_t *ui_TextAreaAppId;
lv_obj_t *ui_PanelLocation;
lv_obj_t *ui_LabelLat;
void ui_event_TextAreaLatitude( lv_event_t * e);
lv_obj_t *ui_TextAreaLatitude;
lv_obj_t *ui_LabelLon;
void ui_event_TextAreaLongitude( lv_event_t * e);
lv_obj_t *ui_TextAreaLongitude;
lv_obj_t *ui_LabelHoehe;
void ui_event_TextAreaHoehe( lv_event_t * e);
lv_obj_t *ui_TextAreaHoehe;
lv_obj_t *ui_PanelTimezone;
lv_obj_t *ui_LabelZeitzone;
void ui_event_DropdownRegion( lv_event_t * e);
lv_obj_t *ui_DropdownRegion;
lv_obj_t *ui_DropdownCity;
lv_obj_t *ui_PanelBase;
lv_obj_t *ui_LabelBasis;
void ui_event_TextAreaBasis( lv_event_t * e);
lv_obj_t *ui_TextAreaBasis;
lv_obj_t *ui_PanelSensors;
lv_obj_t *ui_SensorName1;
void ui_event_TextAreaSensorName1( lv_event_t * e);
lv_obj_t *ui_TextAreaSensorName1;
lv_obj_t *ui_SensorName2;
void ui_event_TextAreaSensorName2( lv_event_t * e);
lv_obj_t *ui_TextAreaSensorName2;
lv_obj_t *ui_SensorName3;
void ui_event_TextAreaSensorName3( lv_event_t * e);
lv_obj_t *ui_TextAreaSensorName3;
lv_obj_t *ui_PanelStart;
void ui_event_ButtonStarten( lv_event_t * e);
lv_obj_t *ui_ButtonStarten;
lv_obj_t *ui_Label3;
void ui_event_KeyboardText( lv_event_t * e);
lv_obj_t *ui_KeyboardText;
void ui_event_KeyboardNumeric( lv_event_t * e);
lv_obj_t *ui_KeyboardNumeric;


// SCREEN: ui_WeatherstationScreen
void ui_WeatherstationScreen_screen_init(void);
lv_obj_t *ui_WeatherstationScreen;
lv_obj_t *ui_Current;
lv_obj_t *ui_DateTime;
lv_obj_t *ui_Panel15;
lv_obj_t *ui_WeatherIcon;
lv_obj_t *ui_Panel12;
lv_obj_t *ui_LineTempCurrent;
lv_obj_t *ui_TempCurrent;
lv_obj_t *ui_TempCurrentUnit;
lv_obj_t *ui_LineCloudsUvCurrent;
lv_obj_t *ui_PanelCloudsCurrent;
lv_obj_t *ui_CloudsCurrentIcon;
lv_obj_t *ui_CloudsCurrent;
lv_obj_t *ui_CloudsCurrentUnit;
lv_obj_t *ui_PanelUvCurrent;
lv_obj_t *ui_UvCurrentIcon;
lv_obj_t *ui_UvCurrent;
lv_obj_t *ui_Panel13;
lv_obj_t *ui_WindDirectionCurrentIcon;
lv_obj_t *ui_PanelWindCurrent;
lv_obj_t *ui_LineWindSpeedCurrent;
lv_obj_t *ui_WindSpeedCurrent;
lv_obj_t *ui_WindSpeedCurrentUnit;
lv_obj_t *ui_LineWindGustCurrent;
lv_obj_t *ui_WindGustCurrent;
lv_obj_t *ui_WindGustCurrentUnit;
lv_obj_t *ui_PanelSunCurrent;
lv_obj_t *ui_LineSunriseCurrent;
lv_obj_t *ui_SunriseCurrentIcon;
lv_obj_t *ui_SunriseCurrent;
lv_obj_t *ui_LineSunsetCurrent;
lv_obj_t *ui_SunsetCurrentIcon;
lv_obj_t *ui_SunsetCurrent;
lv_obj_t *ui_Base;
lv_obj_t *ui_NameBase;
lv_obj_t *ui_LineTempBase;
lv_obj_t *ui_TempBase;
lv_obj_t *ui_TempBaseUnit;
lv_obj_t *ui_LineHumidityBase;
lv_obj_t *ui_IconHumidityBase;
lv_obj_t *ui_HumidityBase;
lv_obj_t *ui_HumidityBaseIcon;
lv_obj_t *ui_PanelSensorsBase;
lv_obj_t *ui_PanelPM;
lv_obj_t *ui_PM10;
lv_obj_t *ui_PM4;
lv_obj_t *ui_PM2p5;
lv_obj_t *ui_PM1;
lv_obj_t *ui_LabelPM;
lv_obj_t *ui_PanelVOC;
lv_obj_t *ui_VOC;
lv_obj_t *ui_LabelVOC;
lv_obj_t *ui_PanelNOX;
lv_obj_t *ui_NOX;
lv_obj_t *ui_Panel21;
lv_obj_t *ui_LabelNOX1;
lv_obj_t *ui_LabelNOX2;
lv_obj_t *ui_PanelCO2;
lv_obj_t *ui_CO2;
lv_obj_t *ui_Panel23;
lv_obj_t *ui_LabelCO21;
lv_obj_t *ui_LabelCO22;
lv_obj_t *ui_Sensor0;
lv_obj_t *ui_Name0;
lv_obj_t *ui_LineTemp0;
lv_obj_t *ui_Temp0;
lv_obj_t *ui_Unit0;
lv_obj_t *ui_LineHumidity0;
lv_obj_t *ui_ImageHumidity0;
lv_obj_t *ui_Hunidity0;
lv_obj_t *ui_Hunidity0Unit;
lv_obj_t *ui_LinePressure0;
lv_obj_t *ui_ImagePressure0;
lv_obj_t *ui_Pressure0;
lv_obj_t *ui_Pressure0Unit;
lv_obj_t *ui_LineStatus0;
lv_obj_t *ui_ImageVolt0;
lv_obj_t *ui_Volt0;
lv_obj_t *ui_ImageUpdate0;
lv_obj_t *ui_Update0;
lv_obj_t *ui_Sensor1;
lv_obj_t *ui_Name1;
lv_obj_t *ui_LineTemp1;
lv_obj_t *ui_Temp1;
lv_obj_t *ui_Unit1;
lv_obj_t *ui_LineHumidity1;
lv_obj_t *ui_ImageHumidity1;
lv_obj_t *ui_Hunidity1;
lv_obj_t *ui_Hunidity1Unit;
lv_obj_t *ui_LinePressure1;
lv_obj_t *ui_ImagePressure1;
lv_obj_t *ui_Pressure1;
lv_obj_t *ui_Pressure1Unit;
lv_obj_t *ui_LineStatus1;
lv_obj_t *ui_ImageVolt1;
lv_obj_t *ui_Volt1;
lv_obj_t *ui_ImageUpdate1;
lv_obj_t *ui_Update1;
lv_obj_t *ui_Sensor2;
lv_obj_t *ui_Name2;
lv_obj_t *ui_LineTemp2;
lv_obj_t *ui_Temp2;
lv_obj_t *ui_Unit2;
lv_obj_t *ui_LineHumidity2;
lv_obj_t *ui_ImageHumidity2;
lv_obj_t *ui_Hunidity2;
lv_obj_t *ui_Hunidity2Unit;
lv_obj_t *ui_LinePressure2;
lv_obj_t *ui_ImagePressure2;
lv_obj_t *ui_Pressure2;
lv_obj_t *ui_Pressure2Unit;
lv_obj_t *ui_LineStatus2;
lv_obj_t *ui_ImageVolt2;
lv_obj_t *ui_Volt2;
lv_obj_t *ui_ImageUpdate2;
lv_obj_t *ui_Update2;
lv_obj_t *ui_Hourly;
lv_obj_t *ui_HourlyChart;
lv_obj_t *ui_Daily;
lv_obj_t *ui_DailyChart;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SetupScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_SCREEN_LOADED) {
      event_screen_loaded( e );
}
}
void ui_event_ButtonScan( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      event_wifi_scan( e );
}
}
void ui_event_TextAreaPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaPassword);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -150);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_ButtonConnect( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      event_wifi_connect( e );
}
}
void ui_event_TextAreaAppId( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaAppId);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -96);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaLatitude( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardNumeric,  ui_TextAreaLatitude);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_X,  -187);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_Y,  96);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaLongitude( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardNumeric,  ui_TextAreaLongitude);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_X,  110);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_Y,  96);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaHoehe( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardNumeric,  ui_TextAreaHoehe);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_X,  270);
      _ui_basic_set_property(ui_KeyboardNumeric, _UI_BASIC_PROPERTY_POSITION_Y,  96);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_DropdownRegion( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_VALUE_CHANGED) {
      event_value_changed( e );
}
}
void ui_event_TextAreaBasis( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaBasis);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -196);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaSensorName1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaSensorName1);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -140);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaSensorName2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaSensorName2);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -140);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_TextAreaSensorName3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_FOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
      _ui_keyboard_set_target(ui_KeyboardText,  ui_TextAreaSensorName3);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_X,  0);
      _ui_basic_set_property(ui_KeyboardText, _UI_BASIC_PROPERTY_POSITION_Y,  -140);
}
if ( event_code == LV_EVENT_DEFOCUSED) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_ButtonStarten( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_WeatherstationScreen, LV_SCR_LOAD_ANIM_NONE, 500, 0, &ui_WeatherstationScreen_screen_init);
      event_weatherstation_start( e );
}
}
void ui_event_KeyboardText( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CANCEL) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}
void ui_event_KeyboardNumeric( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_CANCEL) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_SetupScreen_screen_init();
ui_WeatherstationScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_SetupScreen);
}
