// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_SetupScreen
void ui_SetupScreen_screen_init(void);
void ui_event_SetupScreen( lv_event_t * e);
extern lv_obj_t *ui_SetupScreen;
extern lv_obj_t *ui_PanelSetup;
extern lv_obj_t *ui_PanelNetworks;
extern lv_obj_t *ui_LabelNetworks;
extern lv_obj_t *ui_DropdownNetworks;
void ui_event_ButtonScan( lv_event_t * e);
extern lv_obj_t *ui_ButtonScan;
extern lv_obj_t *ui_LabelScan;
extern lv_obj_t *ui_PanelPassword;
extern lv_obj_t *ui_LabelPassword;
void ui_event_TextAreaPassword( lv_event_t * e);
extern lv_obj_t *ui_TextAreaPassword;
void ui_event_ButtonConnect( lv_event_t * e);
extern lv_obj_t *ui_ButtonConnect;
extern lv_obj_t *ui_LabelScan1;
extern lv_obj_t *ui_PanelAppId;
extern lv_obj_t *ui_LabelAppId;
void ui_event_TextAreaAppId( lv_event_t * e);
extern lv_obj_t *ui_TextAreaAppId;
extern lv_obj_t *ui_PanelLocation;
extern lv_obj_t *ui_LabelLat;
void ui_event_TextAreaLatitude( lv_event_t * e);
extern lv_obj_t *ui_TextAreaLatitude;
extern lv_obj_t *ui_LabelLon;
void ui_event_TextAreaLongitude( lv_event_t * e);
extern lv_obj_t *ui_TextAreaLongitude;
extern lv_obj_t *ui_LabelHoehe;
void ui_event_TextAreaHoehe( lv_event_t * e);
extern lv_obj_t *ui_TextAreaHoehe;
extern lv_obj_t *ui_PanelTimezone;
extern lv_obj_t *ui_LabelZeitzone;
void ui_event_DropdownRegion( lv_event_t * e);
extern lv_obj_t *ui_DropdownRegion;
extern lv_obj_t *ui_DropdownCity;
extern lv_obj_t *ui_PanelBase;
extern lv_obj_t *ui_LabelBasis;
void ui_event_TextAreaBasis( lv_event_t * e);
extern lv_obj_t *ui_TextAreaBasis;
extern lv_obj_t *ui_PanelSensors;
extern lv_obj_t *ui_SensorName1;
void ui_event_TextAreaSensorName1( lv_event_t * e);
extern lv_obj_t *ui_TextAreaSensorName1;
extern lv_obj_t *ui_SensorName2;
void ui_event_TextAreaSensorName2( lv_event_t * e);
extern lv_obj_t *ui_TextAreaSensorName2;
extern lv_obj_t *ui_SensorName3;
void ui_event_TextAreaSensorName3( lv_event_t * e);
extern lv_obj_t *ui_TextAreaSensorName3;
extern lv_obj_t *ui_PanelStart;
void ui_event_ButtonStarten( lv_event_t * e);
extern lv_obj_t *ui_ButtonStarten;
extern lv_obj_t *ui_Label3;
void ui_event_KeyboardText( lv_event_t * e);
extern lv_obj_t *ui_KeyboardText;
void ui_event_KeyboardNumeric( lv_event_t * e);
extern lv_obj_t *ui_KeyboardNumeric;
// SCREEN: ui_WeatherstationScreen
void ui_WeatherstationScreen_screen_init(void);
extern lv_obj_t *ui_WeatherstationScreen;
extern lv_obj_t *ui_Current;
extern lv_obj_t *ui_DateTime;
extern lv_obj_t *ui_Panel15;
extern lv_obj_t *ui_WeatherIcon;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_LineTempCurrent;
extern lv_obj_t *ui_TempCurrent;
extern lv_obj_t *ui_TempCurrentUnit;
extern lv_obj_t *ui_LineCloudsUvCurrent;
extern lv_obj_t *ui_PanelCloudsCurrent;
extern lv_obj_t *ui_CloudsCurrentIcon;
extern lv_obj_t *ui_CloudsCurrent;
extern lv_obj_t *ui_CloudsCurrentUnit;
extern lv_obj_t *ui_PanelUvCurrent;
extern lv_obj_t *ui_UvCurrentIcon;
extern lv_obj_t *ui_UvCurrent;
extern lv_obj_t *ui_Panel13;
extern lv_obj_t *ui_WindDirectionCurrentIcon;
extern lv_obj_t *ui_PanelWindCurrent;
extern lv_obj_t *ui_LineWindSpeedCurrent;
extern lv_obj_t *ui_WindSpeedCurrent;
extern lv_obj_t *ui_WindSpeedCurrentUnit;
extern lv_obj_t *ui_LineWindGustCurrent;
extern lv_obj_t *ui_WindGustCurrent;
extern lv_obj_t *ui_WindGustCurrentUnit;
extern lv_obj_t *ui_PanelSunCurrent;
extern lv_obj_t *ui_LineSunriseCurrent;
extern lv_obj_t *ui_SunriseCurrentIcon;
extern lv_obj_t *ui_SunriseCurrent;
extern lv_obj_t *ui_LineSunsetCurrent;
extern lv_obj_t *ui_SunsetCurrentIcon;
extern lv_obj_t *ui_SunsetCurrent;
extern lv_obj_t *ui_Base;
extern lv_obj_t *ui_NameBase;
extern lv_obj_t *ui_LineTempBase;
extern lv_obj_t *ui_TempBase;
extern lv_obj_t *ui_TempBaseUnit;
extern lv_obj_t *ui_LineHumidityBase;
extern lv_obj_t *ui_IconHumidityBase;
extern lv_obj_t *ui_HumidityBase;
extern lv_obj_t *ui_HumidityBaseIcon;
extern lv_obj_t *ui_PanelSensorsBase;
extern lv_obj_t *ui_PanelPM;
extern lv_obj_t *ui_PM10;
extern lv_obj_t *ui_PM4;
extern lv_obj_t *ui_PM2p5;
extern lv_obj_t *ui_PM1;
extern lv_obj_t *ui_LabelPM;
extern lv_obj_t *ui_PanelVOC;
extern lv_obj_t *ui_VOC;
extern lv_obj_t *ui_LabelVOC;
extern lv_obj_t *ui_PanelNOX;
extern lv_obj_t *ui_NOX;
extern lv_obj_t *ui_Panel21;
extern lv_obj_t *ui_LabelNOX1;
extern lv_obj_t *ui_LabelNOX2;
extern lv_obj_t *ui_PanelCO2;
extern lv_obj_t *ui_CO2;
extern lv_obj_t *ui_Panel23;
extern lv_obj_t *ui_LabelCO21;
extern lv_obj_t *ui_LabelCO22;
extern lv_obj_t *ui_Sensor0;
extern lv_obj_t *ui_Name0;
extern lv_obj_t *ui_LineTemp0;
extern lv_obj_t *ui_Temp0;
extern lv_obj_t *ui_Unit0;
extern lv_obj_t *ui_LineHumidity0;
extern lv_obj_t *ui_ImageHumidity0;
extern lv_obj_t *ui_Hunidity0;
extern lv_obj_t *ui_Hunidity0Unit;
extern lv_obj_t *ui_LinePressure0;
extern lv_obj_t *ui_ImagePressure0;
extern lv_obj_t *ui_Pressure0;
extern lv_obj_t *ui_Pressure0Unit;
extern lv_obj_t *ui_LineStatus0;
extern lv_obj_t *ui_ImageVolt0;
extern lv_obj_t *ui_Volt0;
extern lv_obj_t *ui_ImageUpdate0;
extern lv_obj_t *ui_Update0;
extern lv_obj_t *ui_Sensor1;
extern lv_obj_t *ui_Name1;
extern lv_obj_t *ui_LineTemp1;
extern lv_obj_t *ui_Temp1;
extern lv_obj_t *ui_Unit1;
extern lv_obj_t *ui_LineHumidity1;
extern lv_obj_t *ui_ImageHumidity1;
extern lv_obj_t *ui_Hunidity1;
extern lv_obj_t *ui_Hunidity1Unit;
extern lv_obj_t *ui_LinePressure1;
extern lv_obj_t *ui_ImagePressure1;
extern lv_obj_t *ui_Pressure1;
extern lv_obj_t *ui_Pressure1Unit;
extern lv_obj_t *ui_LineStatus1;
extern lv_obj_t *ui_ImageVolt1;
extern lv_obj_t *ui_Volt1;
extern lv_obj_t *ui_ImageUpdate1;
extern lv_obj_t *ui_Update1;
extern lv_obj_t *ui_Sensor2;
extern lv_obj_t *ui_Name2;
extern lv_obj_t *ui_LineTemp2;
extern lv_obj_t *ui_Temp2;
extern lv_obj_t *ui_Unit2;
extern lv_obj_t *ui_LineHumidity2;
extern lv_obj_t *ui_ImageHumidity2;
extern lv_obj_t *ui_Hunidity2;
extern lv_obj_t *ui_Hunidity2Unit;
extern lv_obj_t *ui_LinePressure2;
extern lv_obj_t *ui_ImagePressure2;
extern lv_obj_t *ui_Pressure2;
extern lv_obj_t *ui_Pressure2Unit;
extern lv_obj_t *ui_LineStatus2;
extern lv_obj_t *ui_ImageVolt2;
extern lv_obj_t *ui_Volt2;
extern lv_obj_t *ui_ImageUpdate2;
extern lv_obj_t *ui_Update2;
extern lv_obj_t *ui_Hourly;
extern lv_obj_t *ui_HourlyChart;
extern lv_obj_t *ui_Daily;
extern lv_obj_t *ui_DailyChart;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_04d_png);   // assets\04d.png
LV_IMG_DECLARE( ui_img_cloud_png);   // assets\cloud.png
LV_IMG_DECLARE( ui_img_uv_png);   // assets\uv.png
LV_IMG_DECLARE( ui_img_arrow_png);   // assets\arrow.png
LV_IMG_DECLARE( ui_img_sunrise_png);   // assets\sunrise.png
LV_IMG_DECLARE( ui_img_sunset_png);   // assets\sunset.png
LV_IMG_DECLARE( ui_img_humidity_png);   // assets\humidity.png
LV_IMG_DECLARE( ui_img_pressure_png);   // assets\pressure.png
LV_IMG_DECLARE( ui_img_battery_png);   // assets\battery.png
LV_IMG_DECLARE( ui_img_uhr_png);   // assets\uhr.png
LV_IMG_DECLARE( ui_img_01d_png);   // assets\01d.png
LV_IMG_DECLARE( ui_img_01n_png);   // assets\01n.png
LV_IMG_DECLARE( ui_img_02d_png);   // assets\02d.png
LV_IMG_DECLARE( ui_img_02n_png);   // assets\02n.png
LV_IMG_DECLARE( ui_img_03d_png);   // assets\03d.png
LV_IMG_DECLARE( ui_img_03n_png);   // assets\03n.png
LV_IMG_DECLARE( ui_img_04n_png);   // assets\04n.png
LV_IMG_DECLARE( ui_img_09d_png);   // assets\09d.png
LV_IMG_DECLARE( ui_img_09n_png);   // assets\09n.png
LV_IMG_DECLARE( ui_img_10d_png);   // assets\10d.png
LV_IMG_DECLARE( ui_img_10n_png);   // assets\10n.png
LV_IMG_DECLARE( ui_img_11d_png);   // assets\11d.png
LV_IMG_DECLARE( ui_img_11n_png);   // assets\11n.png
LV_IMG_DECLARE( ui_img_13d_png);   // assets\13d.png
LV_IMG_DECLARE( ui_img_13n_png);   // assets\13n.png
LV_IMG_DECLARE( ui_img_50d_png);   // assets\50d.png
LV_IMG_DECLARE( ui_img_50n_png);   // assets\50n.png

LV_FONT_DECLARE( ui_font_FreeSans10);
LV_FONT_DECLARE( ui_font_FreeSans14);
LV_FONT_DECLARE( ui_font_FreeSans16);
LV_FONT_DECLARE( ui_font_FreeSans18);
LV_FONT_DECLARE( ui_font_FreeSans20);
LV_FONT_DECLARE( ui_font_FreeSans22);
LV_FONT_DECLARE( ui_font_FreeSans24);
LV_FONT_DECLARE( ui_font_FreeSansBold38);
LV_FONT_DECLARE( ui_font_FreeSansBold44);
LV_FONT_DECLARE( ui_font_FreeSansBold46);
LV_FONT_DECLARE( ui_font_FreeSansBold48);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
