// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SetupScreen_screen_init(void)
{
ui_SetupScreen = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_SetupScreen, lv_color_hex(0x96C6FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SetupScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSetup = lv_obj_create(ui_SetupScreen);
lv_obj_set_width( ui_PanelSetup, 790);
lv_obj_set_height( ui_PanelSetup, 470);
lv_obj_set_align( ui_PanelSetup, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelSetup,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelSetup, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PanelSetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelSetup, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelSetup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSetup, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_PanelSetup, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelSetup, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PanelSetup, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PanelSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelNetworks = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelNetworks, lv_pct(100));
lv_obj_set_height( ui_PanelNetworks, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_PanelNetworks, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelNetworks,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelNetworks, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelNetworks, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelNetworks, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelNetworks, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelNetworks, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelNetworks, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelNetworks, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelNetworks = lv_label_create(ui_PanelNetworks);
lv_obj_set_width( ui_LabelNetworks, 100);
lv_obj_set_height( ui_LabelNetworks, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelNetworks, -302 );
lv_obj_set_y( ui_LabelNetworks, -160 );
lv_obj_set_align( ui_LabelNetworks, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelNetworks,"Netzwerk");
lv_obj_set_style_text_font(ui_LabelNetworks, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DropdownNetworks = lv_dropdown_create(ui_PanelNetworks);
lv_dropdown_set_options( ui_DropdownNetworks, "" );
lv_obj_set_height( ui_DropdownNetworks, LV_SIZE_CONTENT);   /// 30
lv_obj_set_flex_grow( ui_DropdownNetworks, 1);
lv_obj_set_x( ui_DropdownNetworks, 13 );
lv_obj_set_y( ui_DropdownNetworks, -159 );
lv_obj_set_align( ui_DropdownNetworks, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownNetworks, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_DropdownNetworks, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DropdownNetworks, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DropdownNetworks, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DropdownNetworks, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DropdownNetworks, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DropdownNetworks, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DropdownNetworks, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DropdownNetworks, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DropdownNetworks, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DropdownNetworks, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DropdownNetworks), &lv_font_montserrat_18,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownNetworks), lv_color_hex(0xE0E0E0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownNetworks), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonScan = lv_btn_create(ui_PanelNetworks);
lv_obj_set_width( ui_ButtonScan, 130);
lv_obj_set_height( ui_ButtonScan, 36);
lv_obj_set_x( ui_ButtonScan, 300 );
lv_obj_set_y( ui_ButtonScan, -168 );
lv_obj_set_align( ui_ButtonScan, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScan, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScan, lv_color_hex(0xF56101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScan, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelScan = lv_label_create(ui_ButtonScan);
lv_obj_set_width( ui_LabelScan, LV_SIZE_CONTENT);  /// 130
lv_obj_set_height( ui_LabelScan, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelScan, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelScan,"Scan");
lv_obj_set_style_text_align(ui_LabelScan, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelScan, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelScan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelScan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelScan, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelScan, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPassword = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelPassword, lv_pct(100));
lv_obj_set_height( ui_PanelPassword, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_PanelPassword, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelPassword,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelPassword, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelPassword, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelPassword, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelPassword, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelPassword, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelPassword, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelPassword, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPassword = lv_label_create(ui_PanelPassword);
lv_obj_set_width( ui_LabelPassword, 100);
lv_obj_set_height( ui_LabelPassword, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPassword, -300 );
lv_obj_set_y( ui_LabelPassword, -100 );
lv_obj_set_align( ui_LabelPassword, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPassword,"Passwort");
lv_obj_set_style_text_font(ui_LabelPassword, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaPassword = lv_textarea_create(ui_PanelPassword);
lv_obj_set_height( ui_TextAreaPassword, LV_SIZE_CONTENT);   /// 40
lv_obj_set_flex_grow( ui_TextAreaPassword, 1);
lv_obj_set_x( ui_TextAreaPassword, 64 );
lv_obj_set_y( ui_TextAreaPassword, -95 );
lv_obj_set_align( ui_TextAreaPassword, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaPassword,true);
lv_obj_clear_flag( ui_TextAreaPassword, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaPassword, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaPassword, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaPassword, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaPassword, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaPassword, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaPassword, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaPassword, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaPassword, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaPassword, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaPassword, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_ButtonConnect = lv_btn_create(ui_PanelPassword);
lv_obj_set_width( ui_ButtonConnect, 130);
lv_obj_set_height( ui_ButtonConnect, 36);
lv_obj_set_x( ui_ButtonConnect, 300 );
lv_obj_set_y( ui_ButtonConnect, -168 );
lv_obj_set_align( ui_ButtonConnect, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonConnect, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonConnect, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonConnect, lv_color_hex(0xF56101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonConnect, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelScan1 = lv_label_create(ui_ButtonConnect);
lv_obj_set_width( ui_LabelScan1, LV_SIZE_CONTENT);  /// 80
lv_obj_set_height( ui_LabelScan1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelScan1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelScan1,"Verbinden");
lv_obj_set_style_text_font(ui_LabelScan1, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelScan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelScan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelScan1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelScan1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelAppId = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelAppId, lv_pct(100));
lv_obj_set_height( ui_PanelAppId, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_PanelAppId, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelAppId,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelAppId, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelAppId, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelAppId, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelAppId, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelAppId, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelAppId, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelAppId, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelAppId = lv_label_create(ui_PanelAppId);
lv_obj_set_width( ui_LabelAppId, 100);
lv_obj_set_height( ui_LabelAppId, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelAppId, -286 );
lv_obj_set_y( ui_LabelAppId, 31 );
lv_obj_set_align( ui_LabelAppId, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelAppId,"AppId");
lv_obj_set_style_text_font(ui_LabelAppId, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaAppId = lv_textarea_create(ui_PanelAppId);
lv_obj_set_height( ui_TextAreaAppId, LV_SIZE_CONTENT);   /// 40
lv_obj_set_flex_grow( ui_TextAreaAppId, 1);
lv_obj_set_x( ui_TextAreaAppId, 64 );
lv_obj_set_y( ui_TextAreaAppId, -95 );
lv_obj_set_align( ui_TextAreaAppId, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaAppId,true);
lv_obj_clear_flag( ui_TextAreaAppId, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaAppId, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaAppId, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaAppId, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaAppId, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaAppId, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaAppId, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaAppId, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaAppId, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaAppId, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaAppId, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaAppId, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PanelLocation = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelLocation, lv_pct(100));
lv_obj_set_height( ui_PanelLocation, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_PanelLocation, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelLocation,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelLocation, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelLocation, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelLocation, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelLocation, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelLocation, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelLocation, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelLocation, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelLat = lv_label_create(ui_PanelLocation);
lv_obj_set_width( ui_LabelLat, 100);
lv_obj_set_height( ui_LabelLat, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelLat, -265 );
lv_obj_set_y( ui_LabelLat, -36 );
lv_obj_set_align( ui_LabelLat, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLat,"Latitude:");
lv_obj_set_style_text_font(ui_LabelLat, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaLatitude = lv_textarea_create(ui_PanelLocation);
lv_obj_set_width( ui_TextAreaLatitude, 160);
lv_obj_set_height( ui_TextAreaLatitude, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaLatitude, 64 );
lv_obj_set_y( ui_TextAreaLatitude, -95 );
lv_obj_set_align( ui_TextAreaLatitude, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaLatitude,true);
lv_obj_clear_flag( ui_TextAreaLatitude, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaLatitude, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaLatitude, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaLatitude, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaLatitude, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaLatitude, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaLatitude, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaLatitude, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaLatitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaLatitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaLatitude, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaLatitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_LabelLon = lv_label_create(ui_PanelLocation);
lv_obj_set_width( ui_LabelLon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelLon, 82 );
lv_obj_set_y( ui_LabelLon, -33 );
lv_obj_set_align( ui_LabelLon, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLon,"Longitude:");
lv_obj_set_style_text_align(ui_LabelLon, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelLon, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelLon, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelLon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelLon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelLon, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaLongitude = lv_textarea_create(ui_PanelLocation);
lv_obj_set_width( ui_TextAreaLongitude, 160);
lv_obj_set_height( ui_TextAreaLongitude, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaLongitude, 64 );
lv_obj_set_y( ui_TextAreaLongitude, -95 );
lv_obj_set_align( ui_TextAreaLongitude, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaLongitude,true);
lv_obj_clear_flag( ui_TextAreaLongitude, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaLongitude, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaLongitude, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaLongitude, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaLongitude, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaLongitude, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaLongitude, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaLongitude, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaLongitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaLongitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaLongitude, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaLongitude, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_LabelHoehe = lv_label_create(ui_PanelLocation);
lv_obj_set_width( ui_LabelHoehe, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHoehe, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHoehe, 82 );
lv_obj_set_y( ui_LabelHoehe, -33 );
lv_obj_set_align( ui_LabelHoehe, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHoehe,"Höhe:");
lv_obj_set_style_text_align(ui_LabelHoehe, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHoehe, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LabelHoehe, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LabelHoehe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LabelHoehe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LabelHoehe, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaHoehe = lv_textarea_create(ui_PanelLocation);
lv_obj_set_height( ui_TextAreaHoehe, LV_SIZE_CONTENT);   /// 40
lv_obj_set_flex_grow( ui_TextAreaHoehe, 1);
lv_obj_set_x( ui_TextAreaHoehe, 64 );
lv_obj_set_y( ui_TextAreaHoehe, -95 );
lv_obj_set_align( ui_TextAreaHoehe, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaHoehe,true);
lv_obj_clear_flag( ui_TextAreaHoehe, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaHoehe, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaHoehe, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaHoehe, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaHoehe, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaHoehe, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaHoehe, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaHoehe, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaHoehe, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaHoehe, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaHoehe, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaHoehe, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PanelTimezone = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelTimezone, lv_pct(100));
lv_obj_set_height( ui_PanelTimezone, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_PanelTimezone, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelTimezone,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelTimezone, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelTimezone, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelTimezone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelTimezone, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelTimezone, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelTimezone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelTimezone, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelZeitzone = lv_label_create(ui_PanelTimezone);
lv_obj_set_width( ui_LabelZeitzone, 100);
lv_obj_set_height( ui_LabelZeitzone, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelZeitzone, -286 );
lv_obj_set_y( ui_LabelZeitzone, 31 );
lv_obj_set_align( ui_LabelZeitzone, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelZeitzone,"Zeitzone:");
lv_obj_set_style_text_font(ui_LabelZeitzone, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DropdownRegion = lv_dropdown_create(ui_PanelTimezone);
lv_dropdown_set_options( ui_DropdownRegion, "" );
lv_obj_set_width( ui_DropdownRegion, 135);
lv_obj_set_height( ui_DropdownRegion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_DropdownRegion, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownRegion, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_DropdownRegion, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DropdownRegion, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DropdownRegion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DropdownRegion, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DropdownRegion, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DropdownRegion, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DropdownRegion, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DropdownRegion, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DropdownRegion, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DropdownRegion, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownRegion), lv_color_hex(0xE0E0E0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownRegion), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DropdownCity = lv_dropdown_create(ui_PanelTimezone);
lv_dropdown_set_options( ui_DropdownCity, "" );
lv_obj_set_height( ui_DropdownCity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_DropdownCity, 1);
lv_obj_set_align( ui_DropdownCity, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_DropdownCity, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_set_style_text_font(ui_DropdownCity, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DropdownCity, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DropdownCity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_DropdownCity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_DropdownCity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_DropdownCity, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_DropdownCity, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_DropdownCity, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_DropdownCity, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_DropdownCity, 6, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_DropdownCity), lv_color_hex(0xE0E0E0),  LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_DropdownCity), 255,  LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelBase = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelBase, lv_pct(100));
lv_obj_set_height( ui_PanelBase, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_PanelBase, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelBase,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelBase, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelBase, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelBase, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelBase, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelBase, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelBase, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelBase, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelBasis = lv_label_create(ui_PanelBase);
lv_obj_set_width( ui_LabelBasis, 100);
lv_obj_set_height( ui_LabelBasis, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelBasis, -286 );
lv_obj_set_y( ui_LabelBasis, 31 );
lv_obj_set_align( ui_LabelBasis, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelBasis,"Basis:");
lv_obj_set_style_text_font(ui_LabelBasis, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaBasis = lv_textarea_create(ui_PanelBase);
lv_obj_set_width( ui_TextAreaBasis, 135);
lv_obj_set_height( ui_TextAreaBasis, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaBasis, 64 );
lv_obj_set_y( ui_TextAreaBasis, -95 );
lv_obj_set_align( ui_TextAreaBasis, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaBasis,true);
lv_obj_clear_flag( ui_TextAreaBasis, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaBasis, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaBasis, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaBasis, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaBasis, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaBasis, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaBasis, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaBasis, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaBasis, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaBasis, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaBasis, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaBasis, 5, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(ui_TextAreaBasis, &ui_font_FreeSans20, LV_PART_SELECTED| LV_STATE_DEFAULT);


ui_PanelSensors = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelSensors, lv_pct(100));
lv_obj_set_height( ui_PanelSensors, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_PanelSensors, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelSensors,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelSensors, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelSensors, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelSensors, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelSensors, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelSensors, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelSensors, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelSensors, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SensorName1 = lv_label_create(ui_PanelSensors);
lv_obj_set_width( ui_SensorName1, 100);
lv_obj_set_height( ui_SensorName1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SensorName1, -265 );
lv_obj_set_y( ui_SensorName1, -36 );
lv_obj_set_align( ui_SensorName1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorName1,"Sensor 1:");
lv_obj_set_style_text_font(ui_SensorName1, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaSensorName1 = lv_textarea_create(ui_PanelSensors);
lv_obj_set_width( ui_TextAreaSensorName1, 135);
lv_obj_set_height( ui_TextAreaSensorName1, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaSensorName1, 64 );
lv_obj_set_y( ui_TextAreaSensorName1, -95 );
lv_obj_set_align( ui_TextAreaSensorName1, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaSensorName1,true);
lv_obj_clear_flag( ui_TextAreaSensorName1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaSensorName1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaSensorName1, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaSensorName1, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaSensorName1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaSensorName1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaSensorName1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaSensorName1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaSensorName1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaSensorName1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaSensorName1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaSensorName1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_SensorName2 = lv_label_create(ui_PanelSensors);
lv_obj_set_height( ui_SensorName2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_SensorName2, 1);
lv_obj_set_x( ui_SensorName2, -265 );
lv_obj_set_y( ui_SensorName2, -36 );
lv_obj_set_align( ui_SensorName2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorName2,"Sensor 2:");
lv_obj_set_style_text_align(ui_SensorName2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SensorName2, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SensorName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SensorName2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SensorName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SensorName2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaSensorName2 = lv_textarea_create(ui_PanelSensors);
lv_obj_set_width( ui_TextAreaSensorName2, 135);
lv_obj_set_height( ui_TextAreaSensorName2, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaSensorName2, 64 );
lv_obj_set_y( ui_TextAreaSensorName2, -95 );
lv_obj_set_align( ui_TextAreaSensorName2, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaSensorName2,true);
lv_obj_clear_flag( ui_TextAreaSensorName2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaSensorName2, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaSensorName2, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaSensorName2, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaSensorName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaSensorName2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaSensorName2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaSensorName2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaSensorName2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaSensorName2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaSensorName2, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaSensorName2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_SensorName3 = lv_label_create(ui_PanelSensors);
lv_obj_set_height( ui_SensorName3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( ui_SensorName3, 1);
lv_obj_set_x( ui_SensorName3, -265 );
lv_obj_set_y( ui_SensorName3, -36 );
lv_obj_set_align( ui_SensorName3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SensorName3,"Sensor 3:");
lv_obj_set_style_text_align(ui_SensorName3, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SensorName3, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_SensorName3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SensorName3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SensorName3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SensorName3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextAreaSensorName3 = lv_textarea_create(ui_PanelSensors);
lv_obj_set_width( ui_TextAreaSensorName3, 135);
lv_obj_set_height( ui_TextAreaSensorName3, LV_SIZE_CONTENT);   /// 40
lv_obj_set_x( ui_TextAreaSensorName3, 64 );
lv_obj_set_y( ui_TextAreaSensorName3, -97 );
lv_obj_set_align( ui_TextAreaSensorName3, LV_ALIGN_CENTER );
lv_textarea_set_one_line(ui_TextAreaSensorName3,true);
lv_obj_clear_flag( ui_TextAreaSensorName3, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_TextAreaSensorName3, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_text_font(ui_TextAreaSensorName3, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TextAreaSensorName3, lv_color_hex(0xE0E0E0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TextAreaSensorName3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_TextAreaSensorName3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_TextAreaSensorName3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_TextAreaSensorName3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TextAreaSensorName3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TextAreaSensorName3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TextAreaSensorName3, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TextAreaSensorName3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);



ui_PanelStart = lv_obj_create(ui_PanelSetup);
lv_obj_set_width( ui_PanelStart, lv_pct(100));
lv_obj_set_flex_grow( ui_PanelStart, 1);
lv_obj_set_align( ui_PanelStart, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelStart,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelStart, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_width(ui_PanelStart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelStart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelStart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelStart, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelStart, 14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonStarten = lv_btn_create(ui_PanelStart);
lv_obj_set_width( ui_ButtonStarten, 130);
lv_obj_set_height( ui_ButtonStarten, 36);
lv_obj_set_x( ui_ButtonStarten, 26 );
lv_obj_set_y( ui_ButtonStarten, 187 );
lv_obj_set_align( ui_ButtonStarten, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonStarten, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonStarten, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonStarten, lv_color_hex(0xF56101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonStarten, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_ButtonStarten);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Starten");
lv_obj_set_style_text_font(ui_Label3, &ui_font_FreeSans20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Label3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Label3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Label3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Label3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KeyboardText = lv_keyboard_create(ui_SetupScreen);
lv_obj_set_width( ui_KeyboardText, 600);
lv_obj_set_height( ui_KeyboardText, 200);
lv_obj_set_x( ui_KeyboardText, -43 );
lv_obj_set_y( ui_KeyboardText, -196 );
lv_obj_add_flag( ui_KeyboardText, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_KeyboardText, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_KeyboardText, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_KeyboardNumeric = lv_keyboard_create(ui_SetupScreen);
lv_keyboard_set_mode(ui_KeyboardNumeric,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_KeyboardNumeric, 230);
lv_obj_set_height( ui_KeyboardNumeric, 200);
lv_obj_set_x( ui_KeyboardNumeric, -187 );
lv_obj_set_y( ui_KeyboardNumeric, 96 );
lv_obj_set_align( ui_KeyboardNumeric, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_KeyboardNumeric, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_bg_color(ui_KeyboardNumeric, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_KeyboardNumeric, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonScan, ui_event_ButtonScan, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaPassword, ui_event_TextAreaPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonConnect, ui_event_ButtonConnect, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaAppId, ui_event_TextAreaAppId, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaLatitude, ui_event_TextAreaLatitude, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaLongitude, ui_event_TextAreaLongitude, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaHoehe, ui_event_TextAreaHoehe, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_DropdownRegion, ui_event_DropdownRegion, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaBasis, ui_event_TextAreaBasis, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaSensorName1, ui_event_TextAreaSensorName1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaSensorName2, ui_event_TextAreaSensorName2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TextAreaSensorName3, ui_event_TextAreaSensorName3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ButtonStarten, ui_event_ButtonStarten, LV_EVENT_ALL, NULL);
lv_keyboard_set_textarea(ui_KeyboardText,ui_TextAreaPassword);
lv_obj_add_event_cb(ui_KeyboardText, ui_event_KeyboardText, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_KeyboardNumeric, ui_event_KeyboardNumeric, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SetupScreen, ui_event_SetupScreen, LV_EVENT_ALL, NULL);

}
